### ISSUE TITLE
Proxifying issues: Failed to authenticate HTTPS connection - Cannot determine the frame size or a corrupted frame was received

### ISSUE THREAD

**Issue by jhdscript** [microsoft/reverse-proxy#1012]
### Describe the bug
I m trying to direct proxify to https://www.google.com and I have fews errors. If someone could help me I appreciate it

```
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HM8RBJSSM1O0" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HM8RBJSSM1O0" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HM8RBJSSM1O0" sending FIN because: "The Socket transport's send loop completed gracefully."
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HM8RBJSSM1O1" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
```

### To Reproduce
```c#
    public class Startup
    {
        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddHttpProxy();
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        public void Configure(IApplicationBuilder app, IHttpProxy httpProxy)
        {
            // Configure our own HttpMessageInvoker for outbound calls for proxy operations
            var sslOptions = new SslClientAuthenticationOptions
            {
                // Leave certs unvalidated for debugging
                RemoteCertificateValidationCallback = delegate { return true; },
                EnabledSslProtocols = SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13
            };
            var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
            {
                UseProxy = false,
                AllowAutoRedirect = true,
                AutomaticDecompression = DecompressionMethods.All,
                UseCookies = true,
                SslOptions = sslOptions
            });

            // Setup our own request transform class
            //var transformer = new CustomTransformer(); // or HttpTransformer.Default;
            var transformer = HttpTransformer.Default;
            var requestOptions = new RequestProxyConfig { Timeout = TimeSpan.FromSeconds(100) };

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                // When using IHttpProxy for direct proxying you are responsible for routing, destination discovery, load balancing, affinity, etc..
                // For an alternate example that includes those features see BasicYarpSample.
                endpoints.Map("/{**catch-all}", async httpContext =>
                {
                    await httpProxy.ProxyAsync(httpContext, "https://www.google.com", httpClient, requestOptions, transformer);
                    //await httpProxy.ProxyAsync(httpContext, httpContext.Request.GetDisplayUrl(), httpClient, requestOptions, transformer);
                    var errorFeature = httpContext.Features.Get<IProxyErrorFeature>();
                    
                    // Check if the proxy operation was successful
                    if (errorFeature != null)
                    {
                        var error = errorFeature.Error;
                        var exception = errorFeature.Exception;
                    }
                });
            });
        }

        /// <summary>
        /// Custom request transformation
        /// </summary>
        private class CustomTransformer : HttpTransformer
        {
            /// <summary>
            /// A callback that is invoked prior to sending the proxied request. All HttpRequestMessage
            /// fields are initialized except RequestUri, which will be initialized after the
            /// callback if no value is provided. The string parameter represents the destination
            /// URI prefix that should be used when constructing the RequestUri. The headers
            /// are copied by the base implementation, excluding some protocol headers like HTTP/2
            /// pseudo headers (":authority").
            /// </summary>
            /// <param name="httpContext">The incoming request.</param>
            /// <param name="proxyRequest">The outgoing proxy request.</param>
            /// <param name="destinationPrefix">The uri prefix for the selected destination server which can be used to create
            /// the RequestUri.</param>
            public override async ValueTask TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, string destinationPrefix)
            {
                // Copy all request headers
                await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);

                // Customize the query string:
                var queryContext = new QueryTransformContext(httpContext.Request);
                queryContext.Collection.Remove("param1");
                queryContext.Collection["area"] = "xx2";

                // Assign the custom uri. Be careful about extra slashes when concatenating here.
                proxyRequest.RequestUri = new Uri(destinationPrefix + httpContext.Request.Path + queryContext.QueryString);

                // Suppress the original request header, use the one from the destination Uri.
                proxyRequest.Headers.Host = null;
            }
        }
    }
```

### Further technical details

Windows 10, Framework 5

**Comment by karelz** [comment]
@jhdscript it seems you are getting failures on incoming connections - can you check who is connecting to your YARP instance and if they have indeed corrupted HTTPS connection?

**Comment by jhdscript** [comment]
Hello, I defined proxy settings in Firefox to my yarp instance and i try to navigate to google. So the client is Firefox. Regards

**Comment by karelz** [comment]
@jhdscript YARP is reverse-proxy, it cannot be used as forward proxy in browsers like Firefox - that requires different approach and is usually served over HTTP (without S).
You might want to check out [articles on differences](https://www.bing.com/search?q=difference+between+proxy+and+reverse+proxy&cvid=08c3da2b98fe4fed8f45e4c4253be565&aqs=edge.4.0j69i57j0l5.6314j0j1&pglt=515&FORM=ANNAB1&PC=U531) between proxy and reverse proxy like [this one](https://simplicable.com/new/proxy-vs-reverse-proxy#:~:text=Proxy%20vs%20Reverse%20Proxy%20%20%20%20,%20HardwareSoftware%20Service%20%201%20more%20rows%20).

**Comment by jhdscript** [comment]
I dont found any forward proxy in .net, when i look for i m redirected to Yarp :/

**Comment by karelz** [comment]
Why do you need forward proxy in .NET? Why does the language/platform matter to you?

**Comment by karelz** [comment]
Triage: YARP/ASP.NET are not relevant for forward proxy. Closing.
