### ISSUE TITLE
System.InvalidOperationException: Headers already sent

### ISSUE THREAD

**Issue by xljiulang** [microsoft/reverse-proxy#1025]
### Describe the bug
2021-05-26 17:25:39.092 +08:00 [ERR]
Serilog.AspNetCore.RequestLoggingMiddleware
HTTP POST /API/RKEApi/Log/UploadImage responded 500 in 129780.3105 ms
System.InvalidOperationException: Headers already sent.
   at Microsoft.AspNetCore.Server.HttpSys.Response.CheckResponseStarted()
   at Microsoft.AspNetCore.Server.HttpSys.Response.set_StatusCode(Int32 value)
   at Yarp.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer)
   at Yarp.ReverseProxy.Middleware.ProxyInvokerMiddleware.Invoke(HttpContext context)
   at Yarp.ReverseProxy.Middleware.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)

2021-05-26 17:25:39.103 +08:00 [ERR]
Microsoft.AspNetCore.Server.HttpSys.HttpSysListener
ProcessRequestAsync
System.InvalidOperationException: Headers already sent.
   at Microsoft.AspNetCore.Server.HttpSys.Response.CheckResponseStarted()
   at Microsoft.AspNetCore.Server.HttpSys.Response.set_StatusCode(Int32 value)
   at Yarp.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer)
   at Yarp.ReverseProxy.Middleware.ProxyInvokerMiddleware.Invoke(HttpContext context)
   at Yarp.ReverseProxy.Middleware.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext.Execute()
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext.Execute()

### Further technical details

- Include the version of the packages you are using
- The platform (Linux/macOS/Windows)

**Comment by Tratcher** [comment]
We're going to need more information about how to reproduce this error. Please share a minimal app and config that causes this, as well as any information about the specific requests that trigger the error.

**Comment by samsp-msft** [comment]
Triage: Closing due to lack of response. If this is still an issue please reopen.
