### ISSUE TITLE
Parsing integers as TimeSpan results in days

### ISSUE THREAD

**Issue by jaanclaeys** [microsoft/reverse-proxy#1034]
### Describe the bug
When parsing TimeSpan? in general it can conflict what is intended. It should probably work with min and max to alert the user that he is doing wrong. The example in code states for example this [configuration](https://github.com/microsoft/reverse-proxy/tree/main/samples/ReverseProxy.ServiceFabric.Sample#modifying-your-servicemanifest) for servicemanifest
+            <Label Key="YARP.Backend.HealthCheck.Active.Timeout">30</Label>
+            <Label Key="YARP.Backend.HealthCheck.Active.Interval">10</Label>

This will however set the timeout to 30 days and interval to 10 days. If you take values up to 60, then this will even throw an error that it is too large for an int32 in milliseconds.

I do not think this is intended. Solution is to either honour the seconds, or to enforce better limits for these values, so that the user is warned

### To Reproduce

Set the interval of the servicemanifest  for the active healtcheck of the reverseproxy to an integer number above 50:
This will throw following error:

System.ArgumentOutOfRangeException: Time-out interval must be less than 2^32-2. (Parameter 'dueTime')
   at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
   at Yarp.ReverseProxy.Utilities.TimerWrapper.Change(Int64 dueTime, Int64 period) in C:\TFS\SFTest\Src\ReverseProxy\ReverseProxy\Utilities\TimerWrapper.cs:line 19
   at Yarp.ReverseProxy.Service.Management.EntityActionScheduler`1.SchedulerEntry.SetTimer() in C:\TFS\SFTest\Src\ReverseProxy\ReverseProxy\Service\Management\EntityActionScheduler.cs:line 139
   at Yarp.ReverseProxy.Service.Management.EntityActionScheduler`1.SchedulerEntry.ChangePeriod(Int64 newPeriod, Boolean resetTimer) in C:\TFS\SFTest\Src\ReverseProxy\ReverseProxy\Service\Management\EntityActionScheduler.cs:line 131
   at Yarp.ReverseProxy.Service.Management.EntityActionScheduler`1.ChangePeriod(T entity, TimeSpan newPeriod) in C:\TFS\SFTest\Src\ReverseProxy\ReverseProxy\Service\Management\EntityActionScheduler.cs:line 74
   at Yarp.ReverseProxy.Service.HealthChecks.ActiveHealthCheckMonitor.OnClusterChanged(ClusterState cluster) in C:\TFS\SFTest\Src\ReverseProxy\ReverseProxy\Service\HealthChecks\ActiveHealthCheckMonitor.cs:line 87
   at Yarp.ReverseProxy.Service.Management.ProxyConfigManager.UpdateRuntimeClusters(IList`1 incomingClusters) in C:\TFS\SFTest\Src\ReverseProxy\ReverseProxy\Service\Management\ProxyConfigManager.cs:line 373
   at Yarp.ReverseProxy.Service.Management.ProxyConfigManager.ApplyConfigAsync(IProxyConfig config) in C:\TFS\SFTest\Src\ReverseProxy\ReverseProxy\Service\Management\ProxyConfigManager.cs:line 219

### Further technical details

- Include the version of the packages you are using: latest master
- The platform: Windows

**Comment by Tratcher** [comment]
The relevant code:
https://github.com/microsoft/reverse-proxy/blob/6ed1418c71a1dd6a7790036d392d18cbe66a7263/src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs#L298-L299
https://github.com/microsoft/reverse-proxy/blob/6ed1418c71a1dd6a7790036d392d18cbe66a7263/src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs#L40-L62

Here's what we do in the config file provider which has the same issue with integer values:
https://github.com/microsoft/reverse-proxy/blob/6ed1418c71a1dd6a7790036d392d18cbe66a7263/src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs#L278-L279
https://github.com/microsoft/reverse-proxy/blob/6ed1418c71a1dd6a7790036d392d18cbe66a7263/src/ReverseProxy/Utilities/ConfigurationReadingExtensions.cs#L21-L24

**Comment by EgroegKnowles** [comment]
Hello, I'm interested in helping out as I've done something similar in my own project recently. Is anyone tackling this or is it mine to solve?

**Comment by Tratcher** [comment]
Go ahead, thanks.

**Comment by MihaZupan** [comment]
Would we consider accepting formats like `30s` / `10m`? It's not obvious that this is asking for the `0:0:30` format

**Comment by jaanclaeys** [comment]
IMHO: I think the most important is probably changing the READ.me to have an indication of the correct format.

Additionally you might think what min max timespans are a good idea. I guess negative values are not a good idea when doing active healthchecks. But I honestly do not know if intervals longer than a day make (no) sense from a business perspective.

It also depends on the frequency that the proxied service is used I guess. A service that runs once a year, probably benefits enough with an active healthcheck once a day.

**Comment by samsp-msft** [comment]
> Would we consider accepting formats like `30s` / `10m`? It's not obvious that this is asking for the `0:0:30` format

If there is a common timespan parser, sure. I don't think its worth investing in writing our own (the scope of those always creep).

**Comment by samsp-msft** [comment]
Triage: Resolution change to ParseExact so that a "10" value is invalid, but existing correct values will work.
