### ISSUE TITLE
Copying the response body was canceled

### ISSUE THREAD

**Issue by ted-python** [microsoft/reverse-proxy#1149]
### Describe the bug
I put the proxy server between a grpc client and grpc server. And I got the follow exception: 
[09:13:15 INF] ResponseBodyCanceled: Copying the response body was canceled.
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.CancellationHelper.ThrowOperationCanceledException(Exception innerException, CancellationToken cancellationToken)
   at System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.GetCancelableWaiterTask(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.StreamCopier.CopyAsync(Boolean isRequest, Stream input, Stream output, IClock clock, CancellationToken cancellation)

09:13:14 DBG] Connection id "0HM9RKSSF3MA5" accepted.
[09:13:14 DBG] Connection id "0HM9RKSSF3MA5" started.
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received SETTINGS frame for stream ID 0 with length 12 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received HEADERS frame for stream ID 1 with length 4762 and flags END_HEADERS
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 703 and flags NONE
[09:13:14 INF] Request starting HTTP/2 POST some URL application/grpc
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
[09:13:14 INF] Proxying to some URL
[09:13:14 DBG] Connection id "0HM9RKSSF3MA5", Request id "0HM9RKSSF3MA5:00000001": started reading request body.
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending HEADERS frame for stream ID 1 with length 228 and flags END_HEADERS
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 767 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 130 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 70 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 131 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 167 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 128 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 70 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 105 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 56 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 107 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 82 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 644 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 2915 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 151 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 56 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 541 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 6283 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received WINDOW_UPDATE frame for stream ID 1 with length 4 and flags 0x0
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 182 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 56 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 1080 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 5290 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 126 and flags NONE
[09:13:14 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 50 and flags NONE
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 119 and flags NONE
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 50 and flags NONE
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 99 and flags NONE
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" sending DATA frame for stream ID 1 with length 50 and flags NONE
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 0 and flags END_STREAM
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" received RST_STREAM frame for stream ID 1 with length 4 and flags 0x0
[09:13:15 DBG] Connection id "0HM9RKSSF3MA5", Request id "0HM9RKSSF3MA5:00000001": done reading request body.
[09:13:15 INF] ResponseBodyCanceled: Copying the response body was canceled.
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.CancellationHelper.ThrowOperationCanceledException(Exception innerException, CancellationToken cancellationToken)
   at System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.GetCancelableWaiterTask(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.StreamCopier.CopyAsync(Boolean isRequest, Stream input, Stream output, IClock clock, CancellationToken cancellation)
[09:13:15 INF] Request finished in 359.3315ms 200 application/grpc

If I remove the proxy server, everything works fine. Any idea what could cause this?

**Comment by Tratcher** [comment]
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" received DATA frame for stream ID 1 with length 0 and flags END_STREAM
[09:13:15 VRB] Connection id "0HM9RKSSF3MA5" received RST_STREAM frame for stream ID 1 with length 4 and flags 0x0

The client ended the request body and then reset the stream. That triggered the RequestAborted cancellation token which canceled the response body copy loop with the exception reported above. You'll need client logs to figure out why it reset the stream.

**Comment by Tratcher** [comment]
Please re-open if you find additional details relating to YARPs handling of this.
