### ISSUE TITLE
SslStream disposed when file uploading after 100 seconds

### ISSUE THREAD

**Issue by xljiulang** [microsoft/reverse-proxy#1348]
### Describe the bug
```
2021-11-03 09:13:13.462
POST https://objects-origin.githubusercontent.com/github-production-release-asset-2e65be responded 504 in 100011.7272 ms
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
```

### Further technical details

- Include the version of the packages you are using
- The platform (Linux/macOS/Windows)

**Comment by Tratcher** [comment]
Which version of YARP are you using? This timeout behavior was changed in rc1. See https://github.com/microsoft/reverse-proxy/pull/1289

**Comment by xljiulang** [comment]
```
<PackageReference Include="Yarp.ReverseProxy" Version="1.0.0-preview.12.21451.3" />
```

```
2021-11-03T09:25:46.6564341+08:00 [INF]
Yarp.ReverseProxy.Forwarder.HttpForwarder
"RequestTimedOut": The request timed out before receiving a response.
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|138_0(ExceptionDispatchInfo )
   at System.Net.Security.SslStream.ReadAsync(Memory`1 , CancellationToken )
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean )
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   at FastGithub.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)

2021-11-03T09:25:46.7130913+08:00 [WRN]
FastGithub.HttpServer.RequestLoggingMiddleware
POST https://github-production-release-asset-2e65be.s3.amazonaws.com/ responded 504 in 100077.3282 ms
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.

```

**Comment by Tratcher** [comment]
Please update Yarp.ReverseProxy to 1.0.0-rc.1.21520.4 to address this issue.

**Comment by xljiulang** [comment]
thank you

**Comment by xljiulang** [comment]
The problem has been solved!
```
2021-11-03 10:05:09.581
POST https://github-production-release-asset-2e65be.s3.amazonaws.com/ responded 204 in 132672.7057 ms
```
