### ISSUE TITLE
Proxy error handling

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#138]
### Describe the bug
The proxy should catch exceptions from the HttpProxy and convert them to 503s or other statuses as appropriate. This also ties into our [retry](https://github.com/microsoft/reverse-proxy/issues/56) middleware thoughts. Regardless, a common exception like this shouldn't reach Kestrel (which would turn it into a 500).

### To Reproduce
Proxy to a server that isn't currently running.
```
info: Microsoft.ReverseProxy.Core.Middleware.ProxyInvokerMiddleware[9]
      Proxying to https://localhost:10000/api/dump
info: Microsoft.ReverseProxy.Core.Middleware.ProxyInvokerMiddleware[31]
      Operation started: ReverseProxy.Proxy
info: Microsoft.ReverseProxy.Core.Middleware.ProxyInvokerMiddleware[33]
      Operation ended: ReverseProxy.Proxy, 4113.4367ms, error: No connection could be made because the target machine actively refused it.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'backend1/route1'
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLVGE3ID4IFL", Request id "0HLVGE3ID4IFL:00000001": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.MultipleConnectAsync.AsyncFail(Exception e)
   at System.Net.Sockets.MultipleConnectAsync.InternalConnectCallback(Object sender, SocketAsyncEventArgs args)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.HandleCompletionPortCallbackError(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__177_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Core.Service.Proxy.HttpProxy.NormalProxyAsync(HttpContext context, Uri targetUri, HttpMessageInvoker httpClient, ProxyTelemetryContext proxyTelemetryContext, CancellationToken shortCancellation, CancellationToken longCancellation) in D:\github\reverse-proxy\src\ReverseProxy.Core\Service\Proxy\HttpProxy.cs:line 172
   at Microsoft.ReverseProxy.Common.Telemetry.TextOperationLogger`1.ExecuteAsync(String operationName, Func`1 action) in D:\github\reverse-proxy\src\ReverseProxy.Common\Telemetry\TextOperationLogger.cs:line 75
   at Microsoft.ReverseProxy.Core.Middleware.ProxyInvokerMiddleware.Invoke(HttpContext context) in D:\github\reverse-proxy\src\ReverseProxy.Core\Middleware\ProxyInvokerMiddleware.cs:line 97
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/api/dump - - - 500 0 - 4217.8846ms
```

**Comment by Tratcher** [comment]
A note about body error handling from @davidni:

Scenario: Client opens an HTTP/2 channel (gRPC terminology), sends a duplex streaming request, destination server returns a streaming response message indicating it cannot handle the request right now, client reacts by killing the duplex request. It does NOT kill the channel, just that specific duplex request.

Desired behavior: Target server should observe events as if YARP wasn't in the middle. Hence, YARP shoud reset the outgoing request stream, but continue proxying the response stream (?)
 Current behavior: unhandled IOException bubbles out

Question 1: should we also abort the "response" stream copy when the client "request" stream is reset?

Question 2: how to reliably detect this condition. Kestrel throws a very general new IOException(CoreStrings.Http2StreamResetByClient) (source)
```
System.IO.IOException: The client reset the request stream.
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at IslandGateway.Core.Service.Proxy.StreamCopier.CopyAsync(Stream source, Stream destination, CancellationToken cancellation) in C:\source\src\IslandGateway.Core\Service\Proxy\StreamCopier.cs:line 52
   at IslandGateway.Core.Service.Proxy.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context) in C:\source\src\IslandGateway.Core\Service\Proxy\StreamCopyHttpContent.cs:line 150
   at IslandGateway.Core.Service.Proxy.HttpProxy.NormalProxyAsync(HttpContext context, Uri targetUri, HttpMessageInvoker httpClient, ProxyTelemetryContext proxyTelemetryContext, CancellationToken shortCancellation, CancellationToken longCancellation) in C:\source\src\IslandGateway.Core\Service\Proxy\HttpProxy.cs:line 276
```

Stephen Halter:   

> should we also abort the "response" stream copy when the client "request" stream is reset?

Yes. HTTP clients don't use half-open TCP connections.

> how to reliably detect this condition. Kestrel throws a very general

Why special case a client reset vs any other IOException?

Chris:

    The error above says the client sent a reset. A reset HTTP/2 stream is not half-open, it's fully closed. 
    If the client had gracefully ended the request body then an exception wouldn't have been thrown.
    Kestrel and YARP are fine with half-closed requests like that.
    
And yes, any exception from the request body should cause yarp to abort the request body copy loop and cancel the upstream request. This should cause the response loop to fail naturally, but we may want to suppress secondary exceptions from being logged here.

**Comment by samsp-msft** [comment]
Need to be able to convert application errors to:
* Metrics
* Logs
* Specific HTTP Error codes
Based on what transpires in processing a request. What is responsible for returning the response to the client and can formulate the right response.

**Comment by Tratcher** [comment]
Design thoughts:
- As a rule we don't want known exceptions bubbling through the stack. A) They're expensive. B) You're never sure who should catch/handle which exception type.
- The proxy invoker is the boundary between HttpClient and AspNet, it should capture any HttpClient exceptions. Then what?
- Create a proxy result object with the exception, destination information, etc.?
- Set a default status code (503)?
- Flow that result object back in HttpContext.Features and let middleware react to it?
- Something may trigger a retry.

**Comment by Tratcher** [comment]
Design review notes:

Throwing exceptions vs setting request state (feature):
- Throwing has significant perf overhead
- It requires custom exception types if you want to distinguish where the exception came from (e.g. was it from the destination or internal to YARP?)
- It requires a middleware to catch the exceptions and generate status codes.

Proposal:
- The ProxyInvokerMiddleware will catch HttpClient related exceptions as early as possible, assign a default status code (502 or 504), and stash the exception in an HttpContext proxy error Feature.
- Make a ProxyException - not sealed
  - Enum known error types (or put this directly on the feature?)
  - Wraps HttpRequestExceptions & OperationCancelledException from ProxyInvoker
- Middleware can inspect and handle as needed (retry, circuit breakers)
- Other YARP component errors can also set the feature with an enum value for upstack reporting.

**Comment by Tratcher** [comment]
If the response has already started, and it's http/2, consider sending a reset with code INTERNAL_ERROR.
