### ISSUE TITLE
Downstream request becomes malformed when reading body inside builderContext.AddRequestTransform() method

### ISSUE THREAD

**Issue by samanthwal** [microsoft/reverse-proxy#1390]
**Request FROM VS Code  =>**
```
POST https://localhost:9200/app1/api/Values
Content-Type: application/json

  "Hello"
```

**Downstream controller method**
```
  [Route("app1/api/[controller]")]
    [ApiController]
public class ValuesController 
{
 [HttpPost]
        public IActionResult Post([FromBody] string value)
        {
            return Ok(value);
        }

}
```
**Proxy Statup.cs**
```
  private void ConfigureConfig(IServiceCollection services)
        {
            services.AddReverseProxy().LoadFromConfig(Configuration.GetSection("ReverseProxy")).AddTransforms(builderContext =>
            {

                builderContext.AddRequestTransform(async transformcontext =>
                {

                    if (transformcontext.HttpContext.Request.Method == "POST")
                    {
                        transformcontext.HttpContext.Request.EnableBuffering();
                        using var reader = new StreamReader(transformcontext.HttpContext.Request.Body);
                        var body = await reader.ReadToEndAsync();

                        // Parse Body here

                        transformcontext.HttpContext.Request.Body.Seek(0, SeekOrigin.Begin);

                    }
                });
            });
        }


**appsettings.json**


  "ReverseProxy" : {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        //"AuthorizationPolicy": "Default",
        "Match": {
          "Path": "/app1/{**path}"
        }
      }
    },
    "Clusters": {
      "cluster1": {
    
        "Destinations": {
          "cluster1/destination1": {
            **"Address": "https://localhost:6200"**
          }
      }
    }
  }
```
above request works when changing     
```
"cluster1/destination1": {
            "Address": "**http**://localhost:6200"
          }
```
Error Thrown in Downstream service
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IO.IOException: HTTP/2 stream ID 1 error (PROTOCOL_ERROR): Less data received than specified in the Content-Length header.
       ---> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2StreamErrorException: HTTP/2 stream ID 1 error (PROTOCOL_ERROR): Less data received than specified in the Content-Length header.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Stream.OnEndStreamReceived()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Stream.OnDataAsync(Http2Frame dataFrame, ReadOnlySequence`1& payload)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessDataFrameAsync(ReadOnlySequence`1& payload)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
         at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
         at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Tratcher** [comment]
The HttpRequest.Body is captured by the forwarder before transforms run so it's too late to enable buffering inside the transform. Buffering needs to be enabled earlier so the forwarder gets a reference to the buffer stream instead.
https://github.com/microsoft/reverse-proxy/blob/b97621740a5a122802067c04d92d349567817dcd/src/ReverseProxy/Forwarder/HttpForwarder.cs#L289-L293

Also note that StreamReader Disposes the inner stream unless you specify leaveOpen.
https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=net-5.0#System_IO_StreamReader__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean_System_Int32_System_Boolean_

**Comment by samanthwal** [comment]
Thanks Tratcher, I understood that but all of  this works for Htttp endpoint but that error only appears when you have https downstream.

**Comment by Tratcher** [comment]
Works, or fails differently? Without https you will default to HTTP/1.1 instead of HTTP/2 to the backend and the request will be processed differently. The http endpoint still wouldn't receive the full string value.

**Comment by samanthwal** [comment]
downstream http endpoint does receive the string "Hello" in the post method of this downstream service.

public class ValuesController 
{
 [HttpPost]
        public IActionResult Post([FromBody] string value)
        {
            **return Ok(value);**
        }

}

**Comment by Tratcher** [comment]
Hmm, the behavior should not be protocol specific, only the specific error.

**Comment by samanthwal** [comment]
Yes , I was also not expecting the same but encounter it while experimenting with it :)

**Comment by adityamandaleeka** [comment]
@samanthwal Have you tried the solution mentioned above to buffer in middleware?

**Comment by samanthwal** [comment]
> @samanthwal Have you tried the solution mentioned above to buffer in middleware?

Yes , Middleware works fine that I had already tried.

that AddRequestTransform was just an experiment I was doing where I saw https endpoints stopped working.
