### ISSUE TITLE
SSL routines:ssl_choose_client_version:unsupported protocol

### ISSUE THREAD

**Issue by farhadmammadli** [microsoft/reverse-proxy#1443]
### Describe the bug
Cannot setup proper reverse proxy for private remote server which requires tls 1.0 
as this line works
curl -k -v --tlsv1.0 https://192.168.81.3/external/extended	

but this throws ssl error.
curl -k -v https://192.168.81.3/external/extended

As tls 1.0 deprecated and not used by default, i tried to downgrade the minimum tls version for openssl and get the command above working.
sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1.0/g' /etc/ssl/openssl.cnf
sed -i 's/CipherString = DEFAULT@SECLEVEL=2/CipherString = DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf

However, the application itself is throwing ssl error (see the stacktrace). How to solve the problem?

### To Reproduce

To reproduce, the following config was used. 
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "https://192.168.81.3/"
          }
        },
        "HttpClient": {
          "SslProtocols": "Tls",
          "DangerousAcceptAnyServerCertificate": true
        },
        "HttpRequest": {
          "Version": "1.1",
          "VersionPolicy": "RequestVersionOrLower"
        }
      }
    }

12-12 12:09:14.013 [INFO ] Yarp.ReverseProxy.Forwarder.HttpForwarder+Log.ErrorProxying-14 - Request: An error was encountered before receiving a response.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)

### Further technical details

- Dotnet v6.0 (docker)
- OpenSSL 1.1.1k  25 Mar 2021
- Container platform: Debian GNU/Linux 11 (bullseye)

**Comment by farhadmammadli** [comment]
Solved issue by pointing all tls versions
"SslProtocols":[
    "Tls", "Tls11", "Tls12","Tls13"
  ],
