### ISSUE TITLE
PathPattern configuration

### ISSUE THREAD

**Issue by EashShow** [microsoft/reverse-proxy#1517]
### Describe the bug

<details>
```
== APP == info: Yarp.ReverseProxy.Configuration.ConfigProvider.ConfigurationConfigProvider[1]
== APP ==       Loading proxy data from config.
== APP == crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
== APP ==       Application startup exception
== APP ==       System.InvalidOperationException: Unable to load or apply the proxy configuration.
== APP ==        ---> Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route parameter name 'app' appears more than one time in the route template.
== APP ==          at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
== APP ==          at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
== APP ==          at Yarp.ReverseProxy.Transforms.PathRouteValuesTransform..ctor(String pattern, TemplateBinderFactory binderFactory)
== APP ==          at Yarp.ReverseProxy.Transforms.PathTransformFactory.Build(TransformBuilderContext context, IReadOnlyDictionary`2 transformValues)
== APP ==          at Yarp.ReverseProxy.Transforms.Builder.TransformBuilder.BuildInternal(RouteConfig route, ClusterConfig cluster)
== APP ==          at Yarp.ReverseProxy.Transforms.Builder.TransformBuilder.Build(RouteConfig route, ClusterConfig cluster)
== APP ==          at Yarp.ReverseProxy.Management.ProxyConfigManager.BuildRouteModel(RouteConfig source, ClusterState cluster)
== APP ==          at Yarp.ReverseProxy.Management.ProxyConfigManager.UpdateRuntimeRoutes(IList`1 incomingRoutes)
== APP ==          at Yarp.ReverseProxy.Management.ProxyConfigManager.ApplyConfigAsync(IProxyConfig config)
== APP ==          at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
== APP ==          --- End of inner exception stack trace ---
== APP ==          at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
== APP ==          at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
== APP ==          at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints, Action`1 configureApp)
== APP ==          at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints)
== APP ==          at Eachshow.YARP.Startup.<>c.<Configure>b__3_0(IEndpointRouteBuilder endpoints)
== APP ==          at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
== APP ==          at Eachshow.YARP.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
== APP ==          at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
== APP ==          at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
== APP ==          at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)== APP ==          at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
== APP ==          at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
== APP ==          at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
== APP ==          at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)== APP == Unhandled exception. System.InvalidOperationException: Unable to load or apply the proxy configuration.
== APP ==  ---> Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route parameter name 'app' appears more than one time in the route template.
== APP ==    at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
== APP ==    at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
== APP ==    at Yarp.ReverseProxy.Transforms.PathRouteValuesTransform..ctor(String pattern, TemplateBinderFactory binderFactory)
== APP ==    at Yarp.ReverseProxy.Transforms.PathTransformFactory.Build(TransformBuilderContext context, IReadOnlyDictionary`2 transformValues)
== APP ==    at Yarp.ReverseProxy.Transforms.Builder.TransformBuilder.BuildInternal(RouteConfig route, ClusterConfig cluster)
== APP ==    at Yarp.ReverseProxy.Transforms.Builder.TransformBuilder.Build(RouteConfig route, ClusterConfig cluster)
== APP ==    at Yarp.ReverseProxy.Management.ProxyConfigManager.BuildRouteModel(RouteConfig source, ClusterState cluster)
== APP ==    at Yarp.ReverseProxy.Management.ProxyConfigManager.UpdateRuntimeRoutes(IList`1 incomingRoutes)
== APP ==    at Yarp.ReverseProxy.Management.ProxyConfigManager.ApplyConfigAsync(IProxyConfig config)
== APP ==    at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
== APP ==    --- End of inner exception stack trace ---
== APP ==    at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
== APP ==    at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
== APP ==    at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints, Action`1 configureApp)
== APP ==    at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints)
== APP ==    at Eachshow.YARP.Startup.<>c.<Configure>b__3_0(IEndpointRouteBuilder endpoints)
== APP ==    at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
== APP ==    at Eachshow.YARP.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
== APP ==    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
== APP ==    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
== APP ==    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
== APP ==    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
== APP ==    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
== APP ==    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
== APP ==    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
== APP ==    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
== APP ==    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
== APP ==    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
== APP ==    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

</details>

### To Reproduce

config a route like this:
```json
        "Match": {
          "Path": "/{app}/{**remainder}"
        },
        "Transforms": [
          { "PathPattern": "/v1.0/invoke/{app}/method/{app}/{**remainder}" }
        ]
```

### Further technical details

the version of Yarp is V1.0.0
the platform is windows 10

**Comment by Tratcher** [comment]
Hmm, I can see why/how you'd expect that to work. This seems like a limitation of the routing primitives we're using, they were mainly designed for the route matching part of a request where duplicates would not make sense. I'll ask around to see if there is something else we can do here.

Workaround: You'd need to write a custom transform for this.

**Comment by Tratcher** [comment]
This is a limitation of the url generation engine we're using, I don't think we'll be able to change that.

**Comment by EashShow** [comment]
what a pity
: (

**Comment by EashShow** [comment]
what a pity
: (

**Comment by karelz** [comment]
Triage: This is ASP.NET limitation. Nothing we can do about it here. Closing.
If there is significant feedback in ASP.NET, they might change their mind there.
