### ISSUE TITLE
Random 502 Bad gateway response if Content-Length > 65535

### ISSUE THREAD

**Issue by strainovic** [microsoft/reverse-proxy#1624]
Hi,

We're having an issue with service if the response is more than 65k. Even though a response is sent over the network (checked with Wireshark), YARP returns 502 Bad gateway randomly.

```
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderStage :: Stage: SendAsyncStart
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderStage :: Stage: SendAsyncStop
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderStage :: Stage: ResponseContentTransferStart
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnContentTransferred :: Is request: False, Content length: 82411, IOps: 10, Read time: 0.009, Write time: 0.000
[2022-03-29 17:31:52Z INF] ResponseBodyDestination: The destination reported an error when copying the response body.
System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'CANCEL' (0x8).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Boolean isRequest, Stream input, Stream output, IClock clock, ActivityCancellationTokenSource activityToken, CancellationToken cancellation)
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderFailed :: Error: ResponseBodyDestination
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderStop :: Status: 502
[2022-03-29 17:31:52Z ERR] Error while pass-trough of request
System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'CANCEL' (0x8).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Boolean isRequest, Stream input, Stream output, IClock clock, ActivityCancellationTokenSource activityToken, CancellationToken cancellation)
[2022-03-29 17:31:52Z INF] HTTP Response:
Request Method: GET
Request URL: http://localhost:8081/documents/123
Headers: 
  Content-Type: application/json
Status Code: 502
```

There we have two YARPs in a row, and here is a log from the second instance:

```
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderStage :: Stage: SendAsyncStop
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderStage :: Stage: ResponseContentTransferStart
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnContentTransferred :: Is request: False, Content length: 82411, IOps: 12, Read time: 0.007, Write time: 0.000
[2022-03-29 17:31:52Z INF] ResponseBodyDestination: The destination reported an error when copying the response body.
System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'STREAM_CLOSED' (0x5).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Boolean isRequest, Stream input, Stream output, IClock clock, ActivityCancellationTokenSource activityToken, CancellationToken cancellation)
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderFailed :: Error: ResponseBodyDestination
[2022-03-29 17:31:52Z DBG] Forwarder Telemetry => OnForwarderStop :: Status: 200
[2022-03-29 17:31:52Z ERR] Error while passtrough of request
System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'STREAM_CLOSED' (0x5).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Boolean isRequest, Stream input, Stream output, IClock clock, ActivityCancellationTokenSource activityToken, CancellationToken cancellation)
```

With the Wireshark, I found this:

![image](https://user-images.githubusercontent.com/10864240/160769637-7f9f10ef-3b9f-49b9-a07e-42585977043f.png)

It happens randomly, 5 requests are successful, 1-2 are failed...

If Content-Length is 65535 or less, everything works fine.

I tested with YARP `1.0.0` and `1.1.0-rc.1.22152.1`.

Do you have any hints?

**Comment by strainovic** [comment]
Here are some additional findings. If `Content-Lenth` is under or equals 65k, the error rate is exactly 0%.

![image](https://user-images.githubusercontent.com/10864240/160784837-695f9089-f543-42cb-b4a6-9ca7184cfe59.png)

![image](https://user-images.githubusercontent.com/10864240/160786282-19244731-1018-44ab-b541-1db59bc0df98.png)

If `Content-Lenth` is 65k + 1, the error rate is about 58-60%.

![image](https://user-images.githubusercontent.com/10864240/160785180-9a12f8e2-0d9f-4b84-bd8d-fd8b48d808b8.png)

![image](https://user-images.githubusercontent.com/10864240/160785471-61dd3651-5d20-4dc0-b15d-5ef572d3359e.png)

If `Content-Lenth` is ~82k, the error rate is about 24-25%.

![image](https://user-images.githubusercontent.com/10864240/160785737-dd3ab985-ff76-4683-a8b6-3a10fb0632dd.png)

![image](https://user-images.githubusercontent.com/10864240/160785970-c5858a76-d515-4f4d-a6da-2e0a937acba5.png)

**Comment by Tratcher** [comment]
Do you have the logs from the destination server? Was there a request body here? STREAM_CLOSED means the client (YARP) kept sending data to a stream after that stream was closed/aborted.

**Comment by karelz** [comment]
Triage: Looks like Node.js problem, rather than YARP. Closing as it is not actionable on our side.
Thanks!
