### ISSUE TITLE
HttpForwarder failed to send body after update to version 1.1.0-rc.1.22152.1 from 1.0.1

### ISSUE THREAD

**Issue by illay1994** [microsoft/reverse-proxy#1657]
### Describe the bug
We have simple yarp proxy with configuration:
```
        services.AddReverseProxy().LoadFromConfig(Configuration.GetSection("ReverseProxy"));
```
 and 
```

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapReverseProxy();
        });
```

config file:

```
 "ReverseProxy": {
    "Routes": {
      "route": {
        "ClusterId": "cluster",
        "AuthorizationPolicy": "policy",
        "Match": {
          "Path": "/v1/{**remainder}"
        }
      }
    },
    "Clusters": {
      "cluster": {
        "Destinations": {
          "api": {
            "Address": "http://localhost:60825/subpath1/subpath2"
          }
        }
      }
    }
  }
```

### To Reproduce
in version 1.0.1 all working fine

after update to version 1.1.0-rc.1.22152.1 get error in log and return 400 HttpError code

logs:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://192.168.0.2:5000/v1/api application/json;+charset=UTF-8 36
----
internal Authentication logs 
----
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'route'
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://localhost:60825/subpath1/subpath2/v1/api HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      RequestBodyClient: The client reported an error when copying the request body.
      System.AggregateException: One or more errors occurred. (Sent 0 request content bytes, but Content-Length promised 36.) (Error while copying content to a stream.)
       ---> System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 36.
         --- End of inner exception stack trace ---
       ---> (Inner Exception #1) System.Net.Http.HttpRequestException: Error while copying content to a stream.
       ---> System.IO.IOException: An error occurred when reading the request body from the client.
       ---> System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 36.
         --- End of inner exception stack trace ---
         at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)<---

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BasketApiV3Route'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://192.168.0.2:5000/v1/api application/json;+charset=UTF-8 36 - 400 0 - 168.2274ms
```
### Further technical details

- Include the version of the packages you are using 1.1.0-rc.1.22152.1
- net6.0
- Windows 10 and docker image ( mcr.microsoft.com/dotnet/aspnet:6.0)

**Comment by MihaZupan** [comment]
> Sent 0 request content bytes, but Content-Length promised 36.

The error indicates that YARP wasn't able to read any bytes from the request body.
Are you modifying/reading the body in code at any point?

**Comment by illay1994** [comment]
Hi MihaZupan

No.

Client not support http2. 
Client still used http1.1

**Comment by MihaZupan** [comment]
Were these requests that were previously succeeding?

It might be that this is a case where the client disconnected before sending the request content.
Previously this may have shown up as some sort of cancellation, but now it's an input error.

**Comment by illay1994** [comment]
Hi MihaZupan

It is reproduces always.

It is also reproduceble from swagger or curl

**Comment by MihaZupan** [comment]
Can you provide a minimal runnable repro we could try?

**Comment by illay1994** [comment]
It is start reproducing with after merge of this PR
https://github.com/microsoft/reverse-proxy/pull/1415

**Comment by illay1994** [comment]
If you call in any middleware before UseEndpoints

```
 app.Use((context, next) =>
        {
            context.Request.EnableBuffering();
            ....
            return next(context);
        });
```

Proxy will fail

**Comment by Tratcher** [comment]
What's the rest of that middleware look like? Are you remembering to re-wind the request body after you read it?

**Comment by illay1994** [comment]
just this without extra lines
```
 app.Use((context, next) =>
        {
            context.Request.EnableBuffering();
            return next(context);
        });
```
I am planning to delete this middleware.

**Comment by karelz** [comment]
Triage: @illay1994 can you please post a minimal repro (app) for us to check? The code snippets above are not fully helping :(
Thanks!

**Comment by illay1994** [comment]
Code exampe:

https://github.com/illay1994/reverse-proxy/commit/817288da2d6d7e53f47a9969e5423b1d7bae8e38

test url:

curl -X POST "https://localhost:5001/post" -H  "accept: application/json" -d '{"a":123}'

**Comment by Tratcher** [comment]
Thanks, I was able to reproduce this and track it back to https://github.com/dotnet/aspnetcore/issues/41287. EnableBuffering is not compatible with the zero-byte read pattern, that's something we'll need to fix in aspnetcore.

For Triage: recommend closing this as external.

**Comment by Tratcher** [comment]
Related: https://github.com/microsoft/reverse-proxy/issues/1665.

Updated proposal: Skip zero-byte reads for 3.1 and 5.0, and patch AspNetCore 6 for any cases we find.

**Comment by karelz** [comment]
Fixed by https://github.com/microsoft/reverse-proxy/pull/1666

**Comment by 0xStuart** [comment]
I am using yarp to proxy Grafana but I keep getting this error with some of the content.
`System.Net.Http.HttpRequestException: Sent 0 request content bytes, but Content-Length promised 493.`

Googling the issue brought me here.  .Net 7.0.3 and Yarp 2.0  So shouldn't be getting this issue.  Any ideas?

**Comment by johnkors** [comment]
@karelz, this seems to still be an issue. I'm unable to read the request body.

Using a similar approach as OP:

```csharp
app.UseSerilogRequestLogging(options =>
{
    options.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>
    {
        var body = GetRawBodyAsync(httpContext.Request).GetAwaiter().GetResult();
        diagnosticContext.Set("RequestBody", body);
    };
    
    async Task<string> GetRawBodyAsync(HttpRequest request)
    {
        request.EnableBuffering();
        using var reader = new StreamReader(request.Body, Encoding.UTF8);
        var body = await reader.ReadToEndAsync();
        request.Body.Position = 0;
        return body;
    }
});

app.MapReverseProxy(); // 👈 Filtered on certain endpoints & cannot log response body
app.Map("/{**catchall}", Results.BadRequest); // logs response body just fine
```

Using
```xml
<PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
<PackageReference Include="Yarp.ReverseProxy" Version="2.0.1" />
```

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
