### ISSUE TITLE
StreamCopyHttpContent.CreateContentReadStreamAsync() not implemented stops signing code that needs to get a hash of the request body

### ISSUE THREAD

**Issue by EdouardMYOB** [microsoft/reverse-proxy#1695]
### Description

I'm writing a proxy with YARP that signs requests for an upstream service. 

The signature is derived from a hash of: an external key, request method, request path, request headers, and the body itself. The resulting signature is added to the request headers and is validated by the remote server (approximately - the exact details are specified in https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)

I'm currently using https://github.com/FantasticFiasco/aws-signature-version-4 to do the signing, and am integrating it into YARP by using a Request Transform.

Within the transform, the signing code calls `requestContext.ProxyRequest.Content.ReadAsStreamAsync()` so it can calculate a SHA256 on it as part of the signing steps.

The problem here is that `ProxyRequest.Content` is implemented as `StreamCopyHttpContent` from YARP, and the `ReadAsStreamAsync()` simply throws a `NotImplementedException()`.

I'm happy to raise a PR in https://github.com/FantasticFiasco/aws-signature-version-4 if there is a better way of getting the body that works, or failing that, how else should I address the problem of needed to read the request content to add an additional header? 

### To Reproduce
A simple approximation of the issue getting the content stream to hash can be shown by the following:

```
public void ConfigureServices(IServiceCollection services)
{
    var proxyBuilder = services.AddReverseProxy();
    proxyBuilder.LoadFromConfig(Configuration.GetSection("ReverseProxy"));
    
    proxyBuilder.AddTransforms(context =>
    {
        context.AddRequestTransform(async requestContext =>
        {
            using (SHA256 hash = SHA256.Create())
            {
                if (requestContext.ProxyRequest.Content != null)
                {
                    var contentStream = await requestContext.ProxyRequest.Content.ReadAsStreamAsync();
                    var value = await hash.ComputeHashAsync(contentStream);
                    requestContext.ProxyRequest.AddHeader("X-Hash", value.ToString());
                }
            }
        });
    });
}

```

That throws the following:

```
System.NotImplementedException: The method or operation is not implemented.
   at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.CreateContentReadStreamAsync()
   at System.Net.Http.HttpContent.CreateContentReadStreamAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.ReadAsStreamAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.ReadAsStreamAsync()
   at BasicYARPSample.Startup.<>c.<<ConfigureServices>b__7_1>d.MoveNext() in /Users/Edouard.Poor/Projects/YarpPoc/YarpPoc/Startup.cs:line 46
--- End of stack trace from previous location ---
   at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, String destinationPrefix)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activityToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
   at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
   at Yarp.ReverseProxy.Health.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

because StreamCopyHttpContent.CreateContentReadStreamAsync's implementation is:
```
// this is used internally by HttpContent.ReadAsStreamAsync(...)
protected override Task<Stream> CreateContentReadStreamAsync()
{
    // Nobody should be calling this...
    throw new NotImplementedException();
}
```

### Further technical details

- YARP 1.1
- macOS
-

**Comment by EdouardMYOB** [comment]
Closest I can come up with for something that _seems_ to work is to read the Request body, then monkey patch that back into the ProxyRequest:

```
proxyBuilder.AddTransforms(context =>
{
    context.AddRequestTransform(async requestContext =>
    {
        using (SHA256 hash = SHA256.Create())
        {
            if (requestContext.ProxyRequest.Content != null)
            {
                // Replace the ProxyRequest.Content with bytes derived from the Request.Body
                // and monkey patch all the content related headers back again.
                using var reader = new BinaryReader(requestContext.HttpContext.Request.Body);
                using var ms = new MemoryStream();
                await reader.BaseStream.CopyToAsync(ms);
                var bytes = ms.ToArray();
                var oldContentHeaders = requestContext.ProxyRequest.Content.Headers;
                requestContext.ProxyRequest.Content = new ByteArrayContent(bytes);
                requestContext.ProxyRequest.Content.Headers.Clear();
                foreach(var contentHeader in oldContentHeaders)
                    requestContext.ProxyRequest.Content.Headers.Add(contentHeader.Key, contentHeader.Value);

                var contentStream = await requestContext.ProxyRequest.Content.ReadAsStreamAsync();
                var value = await hash.ComputeHashAsync(contentStream);
                requestContext.ProxyRequest.AddHeader("X-Hash", BitConverter.ToString(value));
            }
        }
    });
});
```

Not feeling like that a good long term solution for production code, but interested in the YARP teams thoughts.

**Comment by Tratcher** [comment]
That's about what's recommended in our docs:
https://microsoft.github.io/reverse-proxy/articles/transforms.html#request-body-transforms

The one improvement I'd suggest if you don't need to actually modify the body is to use HttpRequest.EnableBuffering() instead of a MemoryStream. That makes the HttpRequest.Body buffer in place and all you need to do is seek back to the beginning.
That said, there's a bug with EnableBuffering right now that I'm fixing in AspNetCore. https://github.com/microsoft/reverse-proxy/issues/1657#issuecomment-1104481211

**Comment by davidfowl** [comment]
@Tratcher can we add a warning to that sample about the potential for poor performance of the sample? We need to call out performance considerations (and security implications) of things that blindly buffer the entire request body like that.

**Comment by karelz** [comment]
Triage: Let's be more specific in the docs about the warning.

**Comment by davidfowl** [comment]
Generating a header based on the contents of the request body fundamentally buffering the entire response. You can incrementally generate the hash, but the request headers can't be sent until that header is generated, so I'm not sure what an efficient API looks like in this case.
