### ISSUE TITLE
Single bad ingress prevents other ingresses from working

### ISSUE THREAD

**Issue by specialforest** [microsoft/reverse-proxy#1736]
### Describe the bug
K8 controller fails to handle one of ingresses and as a result YARP configuration is empty. 

### To Reproduce
Likely related to a service not having an endpoint because the corresponding pod is in a crash loop.

```
warn: Yarp.Kubernetes.Controller.Services.Reconciler[0]
      Uncaught exception occured while reconciling
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Yarp.Kubernetes.Controller.Converters.YarpParser.HandleIngressRulePath(YarpIngressContext ingressContext, V1ServicePort servicePort, List`1 endpoints, IList`1 defaultSubsets, V1IngressRule rule, V1HTTPIngressPath path, YarpConfigContext configContext) in src\Kubernetes.Controller\Converters\YarpParser.cs:line 79
         at Yarp.Kubernetes.Controller.Converters.YarpParser.HandleIngressRule(YarpIngressContext ingressContext, List`1 endpoints, IList`1 defaultSubsets, V1IngressRule rule, YarpConfigContext configContext) in src\Kubernetes.Controller\Converters\YarpParser.cs:line 44
         at Yarp.Kubernetes.Controller.Converters.YarpParser.ConvertFromKubernetesIngress(YarpIngressContext ingressContext, YarpConfigContext configContext) in src\Kubernetes.Controller\Converters\YarpParser.cs:line 31
         at Yarp.Kubernetes.Controller.Services.Reconciler.ProcessAsync(CancellationToken cancellationToken) in src\Kubernetes.Controller\Services\Reconciler.cs:line 47
```

### Further technical details
Two issues here: 
1. Exception handling in Reconciler.cs makes me think that single bad ingress prevents others from working. Shall it be moved inside the loop?
2. NullReferenceException that I'm trying to debug.

**Comment by specialforest** [comment]
Another issue I noticed here with WorkQueue. After the exception reconciler stops doing anything despite changes to K8 resources.

**Comment by specialforest** [comment]
NullReferenceException  is caused by ports mismatch in service and ingress specs which makes servicePort variable to be null.

E.g.
Service spec has:
```yaml
ports:
- name: https
  port: 10000
  protocol: TCP
  targetPort: 89
```
and Ingress spec has:
```yaml
port:
  number: 443
```

**Comment by specialforest** [comment]
@MihaZupan could you reopen this?

**Comment by specialforest** [comment]
I've published a fix for the issue.

What's missing from the fix is the following case:
1. An Ingress is added and successfully applied to YARP configuration.
2. The Ingress is updated and now Ingress Controller cannot process it. The Ingress spec is valid, but the Ingress Controller has a bug.
Ideally, we want to keep the previous good configuration of the Ingress in place for this case. But current implementation will wipe it out.
