### ISSUE TITLE
At random intervals the application fails to set RouteValues

### ISSUE THREAD

**Issue by okolvik-avento** [microsoft/reverse-proxy#1741]
### Describe the bug
At random intervals (6-24 hours) the application fails to set RouteValues, which raises an exception.
Parallel or subsequent requests completes successfully, it only happens once in a blue moon.
I also had the same bug in Ocelot, so i'm beginning to think it's a framework bug.

Exception:
```
2022-05-29 17:17:54.758 +02:00 [INF] Executing endpoint 'route1'
2022-05-29 17:17:54.759 +02:00 [INF] Proxying to http://192.168.197.14/v3-development/api/global?fields=custObj HTTP/2 RequestVersionOrLower no-streaming
2022-05-29 17:17:54.759 +02:00 [ERR] Connection ID "17509995365712007793", Request ID "80001378-0003-f300-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.set_RouteValues(RouteValueDictionary value)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
2022-05-29 17:17:54.760 +02:00 [INF] Request finished HTTP/1.1 GET http://xx/api/global?fields=custObj - - - 500 - - 4.6533ms
```

Relevant portion of appsettings
```
  "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "AuthorizationPolicy": "default",
        "Match": {
          "Path": "{**catch-all}"
        },
        "AllowAnonymous": false
      }
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "http://192.168.197.13"
          },
          "destination2": {
            "Address": "http://192.168.197.14"
          }
        }
      }
    },
    "LoadBalancingPolicy": "PowerOfTwoChoices"
  }
```
Header and path transformation
```
var proxyBuilder = services.AddReverseProxy();
            // Initialize the reverse proxy from the "ReverseProxy" section of configuration
            proxyBuilder.LoadFromConfig(Configuration.GetSection("ReverseProxy"));
            proxyBuilder.AddTransforms(builderContext =>
                 {
                     // Conditionally add a transform for routes that require auth.
                     if (!string.IsNullOrEmpty(builderContext.Route.AuthorizationPolicy))
                     {
                         builderContext.AddRequestTransform(async transformContext =>
                         {
                             var user = transformContext.HttpContext.User;
                             var version = user.Claims.FirstOrDefault(x => x.Type.Equals("ApiVersion"))?.Value;
                             var hostname = user.Claims.FirstOrDefault(x => x.Type.Equals("ApiHostname"))?.Value;
                             var urlVersion = user.Claims.FirstOrDefault(x => x.Type.Equals("ApiUrlVersion"))?.Value;

                             var environment = _env.EnvironmentName == "Production" ? "" : "-development";
                             if (version != null && hostname != null && urlVersion != null) {
                                 transformContext.ProxyRequest.Headers.Remove("X-Api-Version");
                                 transformContext.ProxyRequest.Headers.Remove("X-Api-Hostname");
                                 transformContext.ProxyRequest.Headers.Add("X-Api-Version", version);
                                 transformContext.ProxyRequest.Headers.Add("X-Api-Hostname", hostname);
                                 transformContext.Path = string.Format("/v{0}{1}{2}", urlVersion, environment, transformContext.Path);
                            }
                         });
                     }
                 });
```

### Further technical details

- Yarp 1.1.0
- Windows Server 2019 with IIS

**Comment by Tratcher** [comment]
A) This doesn't seem to be YARP related, can you move it over to the AspNetCore repo?
B) Does it repro if you disable MiddlewareAnalysis?

**Comment by okolvik-avento** [comment]
> A) This doesn't seem to be YARP related, can you move it over to the AspNetCore repo? B) Does it repro if you disable MiddlewareAnalysis?

A) Sure, i can move it.
B) I don't use MiddlewareAnalysis anywhere myself, i'm guessing it comes from application insights?

**Comment by okolvik-avento** [comment]
Oh wait, i had actually forgotten to remove Ocelot completely. That's the only package that uses Microsoft.AspNetCore.MiddlewareAnalysis. I'm going to remove it now and see how it goes

**Comment by okolvik-avento** [comment]
Filed at AspNetCore repo

**Comment by MihaZupan** [comment]
https://github.com/dotnet/aspnetcore/issues/41924
