### ISSUE TITLE
Multiple domain names forward to different destinations

### ISSUE THREAD

**Issue by ParkerRedford** [microsoft/reverse-proxy#1800]
I'm not sure I am following the docs correctly or the issue is a bug.

I have yarp using kestrel to listen to ports 80 and 443 and two domain names forwarded to different ports. The two domain names are different websites. Yarp responds to only curl commands with a 502 bad gateway error. I got "The token supplied to the function is invalid" when using https

Code:
Yarp =>
```
builder.Services.AddLettuceEncrypt();

builder.WebHost.UseKestrel(options =>
{
    options.ConfigureHttpsDefaults(h =>
    {
        h.ClientCertificateMode = Microsoft.AspNetCore.Server.Kestrel.Https.ClientCertificateMode.RequireCertificate;
        h.UseLettuceEncrypt(options.ApplicationServices);
    });

    options.ListenAnyIP(80);
    options.ListenAnyIP(443);
});
```

Routes and clusters =>
```
var routes = new[]
{
    new RouteConfig()
    {
        RouteId = "route1",
        ClusterId = "cluster1",
        Match = new RouteMatch
        {
            Path = "{**catch-all}",
            Hosts = new[] { "site1.com", "www.site1.com" }
        }
    },
    new RouteConfig()
    {
        RouteId = "route2",
        ClusterId = "cluster2",
        Match = new RouteMatch
        {
            Path = "{**catch-all}",
            Hosts = new[] { "site2.com", "www.site2.com" }
        }
    }
};

var clusters = new[]
{
    new ClusterConfig()
    {
        ClusterId = "cluster1",
        Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
        {
            { "destination1", new DestinationConfig() { Address = "https://localhost:5002" } }
        }
    },
    new ClusterConfig()
    {
        ClusterId = "cluster2",
        Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
        {
            { "destination2", new DestinationConfig() { Address = "https://localhost:5003" } }
        }
    },
};

builder.Services.AddReverseProxy()
    .LoadFromMemory(routes, clusters);
```

api server =>
```
builder.WebHost.ConfigureKestrel((context, options) =>
    {
        var path = Path.Combine("path", "to", "pfx");

        options.ConfigureHttpsDefaults(h =>
        {
            h.ServerCertificate = new System.Security.Cryptography.X509Certificates.X509Certificate2(path, "password");
        });

        options.ListenAnyIP(5001, p => p.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1);

        options.ListenAnyIP(5002, o =>
        {
            o.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2;
            o.UseHttps(path, "password");
        });
    });
```

Dotnet: net6.0
Platform: Linux

**Comment by samsp-msft** [comment]
Can you try the Request Logging, and possibly the Telemetry events from https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html to see if that provides more details as to what is going wrong.

**Comment by ParkerRedford** [comment]
Looks like LettuceEncrypt wasn't loading appsettings.json, so I added it in code.
```
builder.Services.AddLettuceEncrypt(o =>
{
    o.AcceptTermsOfService = true;
    o.DomainNames = new[] { "site1.com", "www.site1.com", "site2.com", "www.site2.com" };
    o.EmailAddress = "email@site1.com";
})
    .PersistDataToDirectory(new DirectoryInfo(path), "password");
```

When I run it, I get "Failed to validate ownership of domainName 'site1.com'. Reason: urn:ietf:params:acme:error:malformed: 108.189.78.128: Server only speaks HTTP, not TLS, Code = BadRequest"

**Comment by samsp-msft** [comment]
If that error is coming back as part of the logging from the YARP process - then there is a problem at the destination server for site1 - do you have https configured for the api server(s) and if you hit those with curl do they work correctly?

**Comment by adityamandaleeka** [comment]
@ParkerRedford Can you share logging from YARP (instructions here: https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html#logging)

And if possible, a diagram of your architecture (including which certs are being used in each part) might be helpful.

**Comment by ParkerRedford** [comment]
All projects are using kestrel.

![YarpDiagram](https://user-images.githubusercontent.com/7292151/179087035-6e754cd7-fe8f-4de1-bb79-9b794637e030.jpg)


This is the error I am getting from Yarp.
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://site1.com/ - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'route1'
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://localhost:5001/ HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'route1'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://site1.com/ - - - 502 0 - 100.4609ms
```

Nothing came up on localhost:5001 or site1.com.

**Comment by Tratcher** [comment]
Ok, so it looks like your API server is using a self-signed certificate that's not trusted by HttpClient/YARP. You can customize the trust on outbound requests via this callback:
https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#configuring-the-http-client
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.remotecertificatevalidationcallback

**Comment by ParkerRedford** [comment]
I am getting "Deference of possibly null reference" error on handler.SslOptions.ClientCertificates

```
var cert = new X509Certificate2(path, "password");
builder.Services.AddReverseProxy()
    .LoadFromMemory(routes, clusters)
    .ConfigureHttpClient((context, handler) =>
{
    handler.SslOptions.ClientCertificates.Add(cert);
});
```

If I run the project I get
```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[62]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Unhandled exception. System.InvalidOperationException: Unable to load or apply the proxy configuration.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.<>c__DisplayClass0_0.<<Main>$>b__2(ForwarderHttpClientContext context, SocketsHttpHandler handler) in C:\Users\Parker\Desktop\ReverseProxy\ReverseProxy\Program.cs:line 100
   at Yarp.ReverseProxy.Forwarder.CallbackHttpClientFactory.ConfigureHandler(ForwarderHttpClientContext context, SocketsHttpHandler handler)
   at Yarp.ReverseProxy.Forwarder.ForwarderHttpClientFactory.CreateClient(ForwarderHttpClientContext context)
   at Yarp.ReverseProxy.Management.ProxyConfigManager.UpdateRuntimeClusters(IEnumerable`1 incomingClusters)
   at Yarp.ReverseProxy.Management.ProxyConfigManager.ApplyConfigAsync(IReadOnlyList`1 routes, IReadOnlyList`1 clusters)
   at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
   --- End of inner exception stack trace ---
   at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints, Action`1 configureApp)
   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints)
   at Program.<>c.<<Main>$>b__0_3(IEndpointRouteBuilder endpoints) in C:\Users\Parker\Desktop\ReverseProxy\ReverseProxy\Program.cs:line 108
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Program.<Main>$(String[] args) in C:\Users\Parker\Desktop\ReverseProxy\ReverseProxy\Program.cs:line 106
Aborted
```
Yarp doesn't get the request if I were to use handler.SslOptions.ClientCertificates?.Add(cert);

**Comment by ParkerRedford** [comment]
Found a working solution for my situation. Not sure for others though.

```
builder.Services.AddReverseProxy()
    .LoadFromMemory(routes, clusters)
    .ConfigureHttpClient((context, handler) =>
    {
        handler.SslOptions.RemoteCertificateValidationCallback = (sender, certificate, chain, chainErrors) => true;
        handler.SslOptions.ClientCertificates = new X509Certificate2Collection();
        handler.SslOptions.ClientCertificates.Add(cert);
    });
```

**Comment by ParkerRedford** [comment]
Got it working I think, here is the solution:
```
var builder = WebApplication.CreateBuilder(args);

var path = Path.Combine("path", "to", "pfx");

builder.Services.AddLettuceEncrypt(o =>
{
    o.AcceptTermsOfService = true;
    o.DomainNames = new[] { "site1.com", "www.site1.com", "site2.com", "www.site2.com" };
    o.EmailAddress = "example@email.com";
})
    .PersistDataToDirectory(new DirectoryInfo(path), "password");

builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenAnyIP(80);
    options.ListenAnyIP(443, o => o.UseHttps(h => h.UseLettuceEncrypt(options.ApplicationServices)));
});

var routes = new[]
{
    new RouteConfig()
    {
        RouteId = "route1",
        ClusterId = "cluster1",
        Match = new RouteMatch
        {
            Path = "{**catch-all}",
            Hosts = new[] { "site1.com", "www.site1.com" },
        },
    },
    new RouteConfig()
    {
        RouteId = "route2",
        ClusterId = "cluster2",
        Match = new RouteMatch
        {
            Path = "{**catch-all}",
            Hosts = new[] { "site2.com", "www.site2.com" }
        }
    }
};

var clusters = new[]
{
    new ClusterConfig()
    {
        ClusterId = "cluster1",
        Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
        {
            { "destination1", new DestinationConfig() { Address = "https://localhost:5001" } }
        },
    },
    new ClusterConfig()
    {
        ClusterId = "cluster2",
        Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
        {
            { "destination2", new DestinationConfig() { Address = "https://localhost:5003" } }
        }
    },
};

var path1 = new X509Certificate2(Path.Combine(path, "cert.pfx"), "password");

builder.Services.AddReverseProxy()
    .LoadFromMemory(routes, clusters)
    .ConfigureHttpClient((context, handler) =>
    {
        handler.SslOptions.RemoteCertificateValidationCallback = (sender, certificate, chain, chainErrors) =>
        {
            if (chainErrors == System.Net.Security.SslPolicyErrors.RemoteCertificateChainErrors)
            {
                chain.ChainPolicy.VerificationFlags |= X509VerificationFlags.IgnoreInvalidPolicy;
                return chain.Build(path1);
            }

            return chainErrors == System.Net.Security.SslPolicyErrors.None;
        };
        handler.SslOptions.ClientCertificates = new X509Certificate2Collection();
        handler.SslOptions.ClientCertificates.Add(path1);
    });

var app = builder.Build();
app.UseHttpsRedirection();

app.UseRouting();

app.UseEndpoints(endpoints =>
{
    endpoints.MapReverseProxy();
});

app.Run();
```

Might want to add the modified handler.SslOptions.RemoteCertificateValidationCallback method in the docs for at least in Debian/Linux.
