### ISSUE TITLE
`TelemetryConsumptionTests.TelemetryConsumptionWorks` sometimes fails with stages out of order

### ISSUE THREAD

**Issue by adityamandaleeka** [microsoft/reverse-proxy#1881]
Observed on local test runs. I can reproduce this if I run the test a few times. I've seen it [in CI too](https://dev.azure.com/dnceng-public/public/_build/results?buildId=40951&view=ms.vss-test-web.build-test-results-tab&runId=824192&resultId=100108&paneView=debug).

```
[xUnit.net 00:00:00.71]     Yarp.ReverseProxy.TelemetryConsumptionTests.TelemetryConsumptionWorks(registrationApproach: Manual) [FAIL]
  Failed Yarp.ReverseProxy.TelemetryConsumptionTests.TelemetryConsumptionWorks(registrationApproach: Manual) [274 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 9)
Expected: ··· "OnHandshakeStop", "OnConnectionEstablished", "OnRequestLeft···
Actual:   ··· "OnHandshakeStop", "OnRequestLeftQueue", "OnConnectionEstabl···
                                 ↑ (pos 9)
  Stack Trace:
     at Yarp.ReverseProxy.TelemetryConsumptionTests.VerifyStages(String[] expected, List`1 stages) in /Users/adityam/code/reverse-proxy/test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs:line 70
   at Yarp.ReverseProxy.TelemetryConsumptionTests.TelemetryConsumptionWorks(RegistrationApproach registrationApproach) in /Users/adityam/code/reverse-proxy/test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs:line 126
--- End of stack trace from previous location ---

```

Looks like the ordering assumption gets violated.

**Comment by adityamandaleeka** [comment]
cc: @mihazupan

**Comment by MihaZupan** [comment]
I can't get this one to reproduce locally.
Can you still see it if you re-enable it?

The only scenario I can imagine where the order of `OnRequestLeftQueue` and `OnConnectionEstablished` would be swapped is if we hit the timeout and the request was canceled right before the connection got established, which is unlikely (I'd be surprised if you could hit it consistently).
