### ISSUE TITLE
`ProxyAsync_RequestWithCookieHeaders` test fails

### ISSUE THREAD

**Issue by adityamandaleeka** [microsoft/reverse-proxy#1884]
Fails on all OS's. Disabled as part of https://github.com/microsoft/reverse-proxy/pull/1841 which is adding FunctionalTests to CI.

```
Error message
System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
```

```c#
Stack trace
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Yarp.ReverseProxy.HttpProxyCookieTests_Http2.ProcessHttpRequest(Uri proxyHostUri) in /_/test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:line 139
   at Yarp.ReverseProxy.HttpProxyCookieTests.<>c__DisplayClass12_0.<<ProxyAsync_RequestWithCookieHeaders>b__3>d.MoveNext() in /_/test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:line 65
--- End of stack trace from previous location ---
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken) in /_/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs:line 89
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken) in /_/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs:line 94
   at Yarp.ReverseProxy.HttpProxyCookieTests.ProxyAsync_RequestWithCookieHeaders() in /_/test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:line 63
--- End of stack trace from previous location ---
```

**Comment by adityamandaleeka** [comment]
Done during #1841
