### ISSUE TITLE
`MultiValueResponseHeaders` failure

### ISSUE THREAD

**Issue by adityamandaleeka** [microsoft/reverse-proxy#1887]
I haven't been able to repro this locally, but it failed on macOS in CI at least once [here](https://dev.azure.com/dnceng-public/public/_build/results?buildId=41032&view=ms.vss-test-web.build-test-results-tab&runId=826262&resultId=100099&paneView=debug).

Case: `Yarp.ReverseProxy.HeaderTests.MultiValueResponseHeaders(headerName: \"Allow\", values: [\"testA=A_Value, testB=B_Value, testC=C_Value\"], expectedValues: [\"testA=A_Value, testB=B_Value, testC=C_Value\"])`

The failure is propagated through the unhandledError capture, so really this is where it's failing:
https://github.com/microsoft/reverse-proxy/blob/5a86eb4f18474bbe2f9e73f8457f4cbf13c00b81/test/ReverseProxy.FunctionalTests/HeaderTests.cs#L646

```
Assert.Null() Failure\nExpected: (null)\nActual:   Xunit.Sdk.TrueException: Assert.True() Failure\n          Expected: True\n          Actual:   False\n             at Xunit.Assert.True(Nullable1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132\n at Yarp.ReverseProxy.HeaderTests.<>c__DisplayClass11_0.<<MultiValueResponseHeaders>b__4>d.MoveNext() in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 646\n --- End of stack trace from previous location ---\n at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)
```

```c#
Stack trace
   at Yarp.ReverseProxy.HeaderTests.<>c__DisplayClass11_0.<<MultiValueResponseHeaders>b__3>d.MoveNext() in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 679
--- End of stack trace from previous location ---
   at Yarp.ReverseProxy.HeaderTests.<>c__DisplayClass11_0.<<MultiValueResponseHeaders>b__3>d.MoveNext() in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 683
--- End of stack trace from previous location ---
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken) in /_/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs:line 89
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken) in /_/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs:line 94
   at Yarp.ReverseProxy.HeaderTests.MultiValueResponseHeaders(String headerName, String[] values, String[] expectedValues) in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 664
--- End of stack trace from previous location ---
```

**Comment by MihaZupan** [comment]
A different sort of failure also hit in CI:

```
Yarp.ReverseProxy.HeaderTests.MultiValueResponseHeaders(headerName: \"Warning\", values: [\"testA=A_Value, testB=B_Value, testC=C_Value\"], expectedValues: [\"testA=A_Value, testB=B_Value, testC=C_Value\"])
```

```
System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.
---- System.Net.Sockets.SocketException : Connection reset by peer
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Yarp.ReverseProxy.HeaderTests.<>c__DisplayClass11_0.<<MultiValueResponseHeaders>b__3>d.MoveNext() in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 676
--- End of stack trace from previous location ---
   at Yarp.ReverseProxy.HeaderTests.<>c__DisplayClass11_0.<<MultiValueResponseHeaders>b__3>d.MoveNext() in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 683
--- End of stack trace from previous location ---
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken) in /_/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs:line 89
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken) in /_/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs:line 94
   at Yarp.ReverseProxy.HeaderTests.MultiValueResponseHeaders(String headerName, String[] values, String[] expectedValues) in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 664
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at System.IO.StreamReader.ReadToEndAsync()
   at Yarp.ReverseProxy.HeaderTests.<>c__DisplayClass11_0.<<MultiValueResponseHeaders>b__3>d.MoveNext() in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 676
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Yarp.ReverseProxy.HeaderTests.<>c__DisplayClass11_0.<MultiValueResponseHeaders>b__3(String proxyUri)
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken) in /_/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs:line 89
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Yarp.ReverseProxy.Common.TestEnvironment.Invoke(Func`2 clientFunc, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.HeaderTests.MultiValueResponseHeaders(String headerName, String[] values, String[] expectedValues) in /_/test/ReverseProxy.FunctionalTests/HeaderTests.cs:line 664
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Yarp.ReverseProxy.HeaderTests.MultiValueResponseHeaders(String headerName, String[] values, String[] expectedValues)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean
```
