### ISSUE TITLE
Multiple routes with wildcard hosts, strange reject(The request matched multiple endpoints)

### ISSUE THREAD

**Issue by WhitePhoera** [microsoft/reverse-proxy#1957]
### Describe the bug
I have config with wildcards for subdomains for different routes(since in production they have different settings), they works in nginx, but not with YARP/ASP.Net Core

### To Reproduce

I use basic yarp app(from Getting started):
ReverseProxy-Routes defined as that:
```json
{
    "route1_root": {
        "ClusterId": "cluster1",
        "Match": {
            "Hosts": [
                "test.ru",
                "*.test.ru",
                "mail.test.ru",
                "www.test.ru"
            ]
        }
    },
    "route2_pages": {
        "ClusterId": "cluster1",
        "Match": {
            "Hosts": [
                "pages.test.ru",
                "*.pages.test.ru",
                "www.pages.test.ru"
            ]
        }
    },
    "route3_t": {
        "ClusterId": "cluster1",
        "Match": {
            "Hosts": [
                "t.test.ru",
                "*.t.test.ru",
                "www.t.test.ru"
            ]
        }
    },
    "route4_x": {
        "ClusterId": "cluster1",
        "Match": {
            "Hosts": [
                "x.test.ru",
                "*.x.test.ru",
                "www.x.test.ru"
            ]
        }
    },
    "route5_com": {
        "ClusterId": "cluster1",
        "Match": {
            "Hosts": [
                "com.test.ru",
                "*.com.test.ru",
                "www.com.test.ru"
            ]
        }
    },
    "route6_faq": {
        "ClusterId": "cluster1",
        "Match": {
            "Hosts": [
                "faq.test.ru",
                "*.faq.test.ru",
                "www.faq.test.ru"
            ]
        }
    }
}
```
When request must use wildcard i get that exception:
```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

route1_root
route4_x
route3_t
route6_faq
route2_pages
route5_com
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: asd.test.ru
User-Agent: PostmanRuntime/7.29.2
Accept-Encoding: gzip, deflate, br
Postman-Token: b551a4d2-8dad-4246-ac86-d8bedac534da
```

any time it uses wildcard match it matches all routes with wildcard and shortest common segment(here if i add test2.ru, it will not be part of selected endpoint)
(same error will be with asd.pages.test.ru, but it must match only one route)

Any ideas how to fix that?

**Comment by samsp-msft** [comment]
It looks like there is abiguity between route1 and the rest of the routes as 
```            
"Hosts": [
                "test.ru",
                "*.test.ru",
                "mail.test.ru",
                "www.test.ru"
```
 "*.test.ru" will also match the other routes. Try putting `"Order": 10` in route1 and see if that makes a difference?

**Comment by WhitePhoera** [comment]
yes, they are intersecting, but i expected it behave like nginx.
also there is still bug that, `asd.faq.test.ru` also have six endpoints as candidates(i expected two at max).

Order helps, issue that those routes are generated actually, so i can't predict them, only way i can try is by length of host with wildcard, but that still sound not good.

also while testing i found that order of routes filtering is random between restarts of app(order of matches in exception) , and, i think, if faq one get tested first, it works fine.
so looks like if initial candidate fails, there is another code at working which then widens lookup even more(so it start to test not `faq.test.ru`, but `test.ru`)

i started writing own IEndpointSelectorPolicy, it feel safer currently, especially with such randomizations in play.

**Comment by Tratcher** [comment]
The misconception here is that you're expecting routing to use a longest-match approach for host names like a server might. However, routing uses a constraints approach to eliminate routes until only one is available. The constraints aren't aware of eachother and can't determine if one is more specific than the other, only that they both match.

**Comment by WhitePhoera** [comment]
>  The constraints aren't aware of eachother and can't determine if one is more specific than the other, only that they both match.
I understand underlying reason, but why all six routes matches?
host from first query must not even match more specific ones,  `asd.test.ru` does not match with `*.faq.test.ru`.
same that `asd.faq.test.ru` does not match `*.pages.test.ru` at all.
This is what mostly confusing for me now.

issue itself is solved by custom IEndpointSelectorPolicy, which rematches hosts and also selects longest match in one go.

**Comment by manusisnova** [comment]
Hi @WhitePhoera 

Can you give an example how you implement IEndpointSelectorPolicy? 

I face the same issue

thank you

**Comment by WhitePhoera** [comment]
```cs
using Microsoft.AspNetCore.Routing.Matching;
using Microsoft.Extensions.Primitives;

public sealed class HostsWildcardPrefixRouteMatcherPolicy : MatcherPolicy, IEndpointSelectorPolicy
{
    public override int Order => 0;

    public bool AppliesToEndpoints(IReadOnlyList<Endpoint> endpoints)
    {
        for (int i = 0; i < endpoints.Count; i++)
        {
            var endpoint = endpoints[i];
            var hosts = endpoint.Metadata.GetMetadata<IHostMetadata>()?.Hosts;
            if (hosts != null)
            {
                for (int j = 0; j < hosts.Count; j++)
                {
                    string? host = hosts[j];
                    if (host.StartsWith("*."))
                        return true;
                }
            }
        }
        return false;
    }

    public Task ApplyAsync(HttpContext httpContext, CandidateSet candidates)
    {
        if (candidates.Count == 1)
            return Task.CompletedTask;
        var host = new StringSegment(httpContext.Request.Host.Host);
        int maxLen = 0;
        int selIndex = -1;
        for (int i = 0; candidates.Count > i; i++)
        {
            var candidate = candidates[i];
            var hosts = candidate.Endpoint.Metadata.GetMetadata<IHostMetadata>()?.Hosts;
            if (hosts != null)
            {
                for (int j = 0; j < hosts.Count; j++)
                {
                    var dhost = new StringSegment(hosts[j]);
                    if (dhost.StartsWith("*.", StringComparison.OrdinalIgnoreCase))
                    {
                        dhost = dhost.Subsegment(2);
                        var chost = host;
                        bool found = false;
                        while (true)
                        {
                            if (dhost.Equals(chost, StringComparison.OrdinalIgnoreCase))
                            {
                                found = true;
                                break;
                            }
                            int index = chost.IndexOf('.');
                            if (index < 0)
                            {
                                break;
                            }
                            chost = chost.Subsegment(index + 1);
                            if (chost.Length < maxLen)
                                break;
                        }
                        if (found && maxLen < dhost.Length)
                        {
                            maxLen = dhost.Length;
                            selIndex = i;
                        }
                    }
                }
            }
        }
        for (int i = 0; candidates.Count > i; i++)
        {
            candidates.SetValidity(i, i == selIndex);
        }
        return Task.CompletedTask;
    }
}
```
This is class i used to make, not fully tested yet, may be you need other order value as well, but on first glance it works.

**Comment by manusisnova** [comment]
thanks so much
