### ISSUE TITLE
Run in a docker container and proxy to grafana, all POST request get bad request, while GET requeset works well.

### ISSUE THREAD

**Issue by bnuzhouwei** [microsoft/reverse-proxy#1966]
### Describe the bug
Run in a docker container and proxy to grafana, all POST request get bad request, while GET requeset works well.

```bash
9512.8f35f1c2de682ecc2973.js:2          POST http://x.x.x.x:5000/core/grafana/api/frontend-metrics 400 (Bad Request)
grafana/?orgId=1:1 Uncaught (in promise) {status: 400, statusText: 'Bad Request', data: {…}, config: {…}}
```

### To Reproduce

"ReverseProxy": {
    "Routes": {
      "route2": {
        "ClusterId": "grafana",
        "Match": {
          "Path": "/core/grafana/{**catch-all}"
        },
        "Transforms": [
          { "PathPattern": "/{**catch-all}" },
          { "RequestHeaderOriginalHost": "true" }
        ]
      }
    },
    "Clusters": {
      "grafana": {
        "Destinations": {
          "destination1": {
            "Address": "grafana:3000"
          }
        }
      }
    }
  },

### Further technical details

- The platform (Ubuntu 22.04, docker-compose)

the logs from docker logs:

```json
{"EventId":9,"LogLevel":"Information","Category":"Yarp.ReverseProxy.Forwarder.HttpForwarder","Message":"Proxying to http://grafana:3000/login HTTP/2 RequestVersionOrLower no-streaming","State":{"Message":"Proxying to http://grafana:3000/login HTTP/2 RequestVersionOrLower no-streaming","targetUrl":"http://grafana:3000/login","version":"HTTP/2","versionPolicy":"RequestVersionOrLower","isStreaming":"no-streaming","{OriginalFormat}":"Proxying to {targetUrl} {version} {versionPolicy} {isStreaming}"}}
{"EventId":48,"LogLevel":"Information","Category":"Yarp.ReverseProxy.Forwarder.HttpForwarder","Message":"RequestBodyClient: The client reported an error when copying the request body.","Exception":"System.AggregateException: One or more errors occurred. (Sent 0 request content bytes, but Content-Length promised 53.) (Error while copying content to a stream.)  ---\u003E System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 53.    --- End of inner exception stack trace ---  ---\u003E (Inner Exception #1) System.Net.Http.HttpRequestException: Error while copying content to a stream.  ---\u003E System.IO.IOException: An error occurred when reading the request body from the client.  ---\u003E System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 53.    --- End of inner exception stack trace ---    at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)    at System.Net.Http.HttpContent.\u003CCopyToAsync\u003Eg__WaitAsync|56_0(ValueTask copyTask)    --- End of inner exception stack trace ---    at System.Net.Http.HttpContent.\u003CCopyToAsync\u003Eg__WaitAsync|56_0(ValueTask copyTask)    at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)\u003C--- ","State":{"Message":"RequestBodyClient: The client reported an error when copying the request body.","error":"RequestBodyClient","message":"The client reported an error when copying the request body.","{OriginalFormat}":"{error}: {message}"}}
```

**Comment by Tratcher** [comment]
That error implies the request body was already read by your proxy app. Do you have middleware reading the body? The body is not buffered by default, you need to enable buffering if you're going to read the body and also proxy it.

**Comment by bnuzhouwei** [comment]
I has EnableBuffering, but the error still has.

```
var app = builder.Build();
app.Use(async (context, next) => {
    context.Request.EnableBuffering();
    await next(context);
});
app.MapReverseProxy();
```



Still has error,

```
{"EventId":48,"LogLevel":"Information","Category":"Yarp.ReverseProxy.Forwarder.HttpForwarder","Message":"RequestBodyClient: The client reported an error when copying the request body.","Exception":"System.AggregateException: One or more errors occurred. (Sent 0 request content bytes, but Content-Length promised 41.) (Error while copying content to a stream.)  ---\u003E System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 41.    --- End of inner exception stack trace ---  ---\u003E (Inner Exception #1) System.Net.Http.HttpRequestException: Error while copying content to a stream.  ---\u003E System.IO.IOException: An error occurred when reading the request body from the client.  ---\u003E System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 41.    --- End of inner exception stack trace ---    at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)    at System.Net.Http.HttpContent.\u003CCopyToAsync\u003Eg__WaitAsync|56_0(ValueTask copyTask)    --- End of inner exception stack trace ---    at System.Net.Http.HttpContent.\u003CCopyToAsync\u003Eg__WaitAsync|56_0(ValueTask copyTask)    at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpMessageInvoker.\u003CSendAsync\u003Eg__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)    at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)\u003C--- ","State":{"Message":"RequestBodyClient: The client reported an error when copying the request body.","error":"RequestBodyClient","message":"The client reported an error when copying the request body.","{OriginalFormat}":"{error}: {message}"}}
{"EventId":9,"LogLevel":"Information","Category":"Yarp.ReverseProxy.Forwarder.HttpForwarder","Message":"Proxying to http://grafana:3000/core/grafana/login HTTP/2 RequestVersionOrLower no-streaming","State":{"Message":"Proxying to http://grafana:3000/core/grafana/login HTTP/2 RequestVersionOrLower no-streaming","targetUrl":"http://grafana:3000/core/grafana/login","version":"HTTP/2","versionPolicy":"RequestVersionOrLower","isStreaming":"no-streaming","{OriginalFormat}":"Proxying to {targetUrl} {version} {versionPolicy} {isStreaming}"}}
{"EventId":48,"LogLevel":"Information","Category":"Yarp.ReverseProxy.Forwarder.HttpForwarder","Message":"RequestBodyClient: The client reported an error when copying the request body.","Exception":"System.AggregateException: One or more errors occurred. (Sent 0 request content bytes, but Content-Length promised 41.) (Error while copying content to a stream.)  ---\u003E System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 41.    --- End of inner exception stack trace ---  ---\u003E (Inner Exception #1) System.Net.Http.HttpRequestException: Error while copying content to a stream.  ---\u003E System.IO.IOException: An error occurred when reading the request body from the client.  ---\u003E System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 41.    --- End of inner exception stack trace ---    at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)    at System.Net.Http.HttpContent.\u003CCopyToAsync\u003Eg__WaitAsync|56_0(ValueTask copyTask)    --- End of inner exception stack trace ---    at System.Net.Http.HttpContent.\u003CCopyToAsync\u003Eg__WaitAsync|56_0(ValueTask copyTask)    at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpMessageInvoker.\u003CSendAsync\u003Eg__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)    at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)\u003C--- ","State":{"Message":"RequestBodyClient: The client reported an error when copying the request body.","error":"RequestBodyClient","message":"The client reported an error when copying the request body.","{OriginalFormat}":"{error}: {message}"}}

```

**Comment by bnuzhouwei** [comment]
IIS with the same error

```
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://8.142.179.204:3000/core/grafana/login HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      RequestBodyClient: The client reported an error when copying the request body.
      System.AggregateException: One or more errors occurred. (Sent 0 request content bytes, but Content-Length promised 35.) (Error while copying content to a stream.)
       ---> System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 35.
         --- End of inner exception stack trace ---
       ---> (Inner Exception #1) System.Net.Http.HttpRequestException: Error while copying content to a stream.
       ---> System.IO.IOException: An error occurred when reading the request body from the client.
       ---> System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 35.
         --- End of inner exception stack trace ---
         at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)<---
```

**Comment by Tratcher** [comment]
What's reading the request body the first time? After it's read into the buffer the Position must be set back to 0.

**Comment by bnuzhouwei** [comment]
The body has been seek to 0

```
if (context.Response.Body.CanSeek) context.Response.Body.Seek(0, SeekOrigin.Begin);
```

**Comment by bnuzhouwei** [comment]
Strange issue, it work on Windows 11 pro, but fail on windows server 2016.

**Comment by bnuzhouwei** [comment]
Solved after upgrade .net runtime to 6.0.12, but why?

**Comment by Tratcher** [comment]
Probably this fix: https://github.com/dotnet/aspnetcore/pull/41410
