### ISSUE TITLE
Socket Exception Prevents Further Requests

### ISSUE THREAD

**Issue by MoMack20** [microsoft/reverse-proxy#2012]
### Describe the bug
I encountered a socket exception and the program seemed to hang afterwards. Any new requests made never resolved and all the information logs (in the event viewer) stopped.

### To Reproduce

My YARP instance has been running out in the wild as a windows service on a windows server 2019 machine. This occurred seemingly at random and I don't have much else to go off of other than the stack trace. There have been a few other occasions when the instance seems to have became unresponsive and I had to restart the service, but that in those cases nothing was logged to the event viewer.

```
Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 0
ConnectionId: 0HMNV1049BG1U

Connection processing ended abnormally.

Exception: 
System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

### Further technical details
The setup was really basic but here it is.

Program.cs
```
await Host.CreateDefaultBuilder(args)
    .UseWindowsService()
    .ConfigureLogging(logging =>
    {
        logging.AddEventLog(configuration => configuration.SourceName = ".NET Runtime");
    }).ConfigureWebHostDefaults(host =>
    {
        host.Configure(app =>
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapReverseProxy();
            });
        });
        host.ConfigureServices((builder, services) =>
        {
            var configuration = builder.Configuration;
            services.AddReverseProxy()
                .LoadFromConfig(configuration.GetSection("ReverseProxy"));
        });
    }).Build()
    .RunAsync();
```

appsettings
```
{
  "Urls": "http://*:80;",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "EventLog": {
      "LogLevel": {
         "Default": "Information"
      }
    }	
  },
  "ReverseProxy": {
    "Routes": {
      "minimumroute": {
        "ClusterId": "Default",
        "Match": {
          "Path": "{**catch-all}"
        }
      },
      "route2": {
        "ClusterId": "cluster2",
        "Match": {
          "Path": "/Test/{*any}"
        }
      }
    },
    "Clusters": {
      "Default": {
	"HttpClient": {
    	   "SslProtocols": ["Tls11"]
	},
	"HttpRequest": {
    	   "ActivityTimeout": "00:10:00",
    	   "Version": "1.1",
    	   "VersionPolicy": "RequestVersionOrLower"
	},
        "Destinations": {
          "example.com": {
            "Address": "http://localhost:5001"
          }
        }
      },
      "RogueApps2": {
        "Destinations": {
          "first_destination": {
            "Address": "http://localhost:59514"
          }
        }
      }
    }
  }
}
```

csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.0" /> 
    <PackageReference Include="Yarp.ReverseProxy" Version="1.1.1" />
  </ItemGroup>
</Project>
```

**Comment by Tratcher** [comment]
When an instance becomes unresponsive the best thing to do is capture a full process dump for analysis. That will let you check for blocked threads, a backed up threadpool, broken sockets, etc.

**Comment by MoMack20** [comment]
Next time the application goes down I'll see if I can get a dump
