### ISSUE TITLE
SignalR random 404's

### ISSUE THREAD

**Issue by jbonnett92** [microsoft/reverse-proxy#2015]
Hi,
I have a cluster and routes that is built from instances in Consul, I manually added a route and cluster for SignalR and looks like so:
```json
  {
    "routeId": "signalr-routes",
    "match": {
      "methods": null,
      "hosts": null,
      "path": "/websocket/{*any}",
      "queryParameters": null,
      "headers": null
    },
    "order": null,
    "clusterId": "signalr",
    "authorizationPolicy": null,
    "corsPolicy": null,
    "metadata": null,
    "transforms": [
      {
        "RequestHeadersCopy": "true"
      },
      {
        "RequestHeaderOriginalHost": "true"
      },
      {
        "RequestHeader": "Upgrade",
        "Set": "WebSocket"
      },
      {
        "RequestHeader": "Connection",
        "Set": "Upgrade"
      },
      {
        "X-Forwarded": "Set",
        "For": "Append",
        "Proto": "Append",
        "Prefix": "Append",
        "HeaderPrefix": "X-Forwarded-"
      }
    ]
  }
```

```json
  {
    "clusterId": "signalr",
    "loadBalancingPolicy": "PowerOfTwoChoices",
    "sessionAffinity": {
      "enabled": true,
      "policy": "CustomHeader",
      "failurePolicy": "Redistribute",
      "affinityKeyName": "ProxySessionAffinity",
      "cookie": null
    },
    "healthCheck": null,
    "httpClient": null,
    "httpRequest": null,
    "destinations": {
      "catalog-http-api-service-398c8213-7abb-40f2-b0ce-15311d05fb51": {
        "address": "http://127.0.0.1:63835/",
        "health": "http://127.0.0.1:63835/health",
        "metadata": null
      },
      "identity-http-api-service-0cf35626-f3cb-4dd5-a4de-363f444e1065": {
        "address": "http://127.0.0.1:63891/",
        "health": "http://127.0.0.1:63891/health",
        "metadata": null
      }
    },
    "metadata": null
  }
```
As you can see the random 404's
<img width="1440" alt="Screenshot 2023-01-30 at 07 08 31" src="https://user-images.githubusercontent.com/3740700/215411163-df596555-a2fc-4475-9b16-726b867f7e9f.png">
They actually get worse with RoundRobin, if I get a connection at all!

If I take the addresses in the config and manually add them to the SignalR client, it works perfectly for every service.

I don't get any exceptions, though I do get the following output:
```
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59947/websocket/negotiate?negotiateVersion=1 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 200.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59973/websocket?id=JWjdEJVK8wUnKNpUXGVGlQ&_=1675063139950 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 404.

```

This is the console with RoundRobin:
<img width="1440" alt="Screenshot 2023-01-30 at 07 18 11" src="https://user-images.githubusercontent.com/3740700/215411999-37bd6ed2-7ac2-4ba0-96b4-5c6208eaf0ff.png">

I think I have setup session affinity correctly by adding this along with the config
```csharp
app.MapReverseProxy(opt => {
    opt.UseSessionAffinity();
    opt.UseLoadBalancing();
});
```
But I have either not applied it correctly or there is a bug. Though does look to be session affinity.

**Comment by jbonnett92** [comment]
Turns out I just needed to remove the key `Policy` from the session affinity config. Why is this?

**Comment by jbonnett92** [comment]
Ok it is not fixed, it works in Safari, but not Chrome...

**Comment by jbonnett92** [comment]
I have tried two more browsers, it doesn't work on Opera, but does work on Firefox.

**Comment by Tratcher** [comment]
Try this:
https://github.com/microsoft/reverse-proxy/issues/1158#issuecomment-884357315

**Comment by jbonnett92** [comment]
> Try this: [#1158 (comment)](https://github.com/microsoft/reverse-proxy/issues/1158#issuecomment-884357315)

I was already using that issue as a guide.

**Comment by jbonnett92** [comment]
Safari (Working) with two refreshes:
```yaml
warn: Yarp.ReverseProxy.SessionAffinity.CookieSessionAffinityPolicy[39]
      Destination matching to the request affinity key is not found on cluster `signalr`. Configured failure policy will be applied.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59291/websocket/negotiate?negotiateVersion=1 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59291/api/identity/users HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 200.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59291/websocket?id=c2GQOrDquUtwquQfljzMDA HTTP/1.1 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 101.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 200.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      UpgradeResponseCanceled: Copying the upgraded response body was canceled.
      System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
       ---> System.Net.Sockets.SocketException (89): Operation canceled
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
         at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, CancellationToken cancellation)
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59291/api/identity/users HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59291/websocket/negotiate?negotiateVersion=1 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 200.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to http://127.0.0.1:59291/websocket?id=8r050QH1OaLOV4RHpdjROg HTTP/1.1 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 101.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 200.
```

**Comment by jbonnett92** [comment]
After setting it to secure it worked perfectly:
```json
"clusterId": "signalr",
    "loadBalancingPolicy": "RoundRobin",
    "sessionAffinity": {
      "enabled": true,
      "policy": "Cookie",
      "failurePolicy": "Redistribute",
      "affinityKeyName": "ProxySessionAffinity",
      "cookie": {
        "path": null,
        "domain": null,
        "httpOnly": true,
        "securePolicy": 1,
        "sameSite": 0,
        "expiration": null,
        "maxAge": null,
        "isEssential": true
      }
    },
```
Code:
```csharp
ClusterConfig cluster = new()
{
    ClusterId = "signalr",
    LoadBalancingPolicy = LoadBalancingPolicies.RoundRobin,
    Destinations = _clusterDestinations["signalr"],
    SessionAffinity = new()
    {
        Enabled = true,
        Policy = "Cookie",
        AffinityKeyName = "ProxySessionAffinity",
        FailurePolicy = "Redistribute",
        Cookie = new()
        {
            SameSite = SameSiteMode.None,
            SecurePolicy = CookieSecurePolicy.Always,
            HttpOnly = true,
            IsEssential = true
        }
    }
};
```
