### ISSUE TITLE
Documentation Maintenance For Kubernetes Controller

### ISSUE THREAD

**Issue by nquandt** [microsoft/reverse-proxy#2018]
### What should we add or change to make your life better?

  I noticed an update to the Kubernetes.Controller by @witskeeper, I realize now that "reviewing" a completed PR will probably not be noticed, so I submitting this issue as reference.
  #1913 

### Why is this important to you?

Required configurations should be mentioned / documented somewhere when changed.

![image](https://user-images.githubusercontent.com/57432850/215622172-ea85358e-83a0-4ba7-ba5b-5342b621be31.png)

**Comment by MihaZupan** [comment]
I agree, at a minimum, it would be worth commenting on the `YarpOptions` when things are deemed required and updating examples to match. If there are any required settings, we should also validate that and fail early.

Even if updating the status failed, we likely shouldn't prevent the reconciler loop from continuing.

**Comment by specialforest** [comment]
Also need `get` on `ingresses/status`. Samples don't have it.

**Comment by specialforest** [comment]
Could you please update the title to make the bug searchable? 

Nevertheless, reposting error stack trace:
```
warn: Yarp.Kubernetes.Controller.Services.Reconciler[0]
      Uncaught exception occured while reconciling
      System.ArgumentNullException: Value cannot be null. (Parameter 'name')
         at k8s.AbstractKubernetes.k8s.ICoreV1Operations.ReadNamespacedServiceStatusWithHttpMessagesAsync(String name, String namespaceParameter, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
         at k8s.CoreV1OperationsExtensions.ReadNamespacedServiceStatusAsync(ICoreV1Operations operations, String name, String namespaceParameter, Nullable`1 pretty, CancellationToken cancellationToken)
         at Yarp.Kubernetes.Controller.Client.V1IngressResourceStatusUpdater.UpdateStatusAsync()
         at Yarp.Kubernetes.Controller.Services.Reconciler.ProcessAsync(CancellationToken cancellationToken) in src\Kubernetes.Controller\Services\Reconciler.cs:line 71
```
and keywords ControllerServiceName ControllerServiceNamespace.

**Comment by specialforest** [comment]
Also it updates a status of all ingresses in the cluster without `IsYarpIngress` check :(
