### ISSUE TITLE
Sent 0 request content bytes, but Content-Length promised 163

### ISSUE THREAD

**Issue by 3087897260** [microsoft/reverse-proxy#2125]
```
System.AggregateException: One or more errors occurred. (Sent 0 request content bytes, but Content-Length promised 163.) (Error while copying content to a stream.)
 ---> System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 163.
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: An error occurred when reading the request body from the client.
 ---> System.InvalidOperationException: Sent 0 request content bytes, but Content-Length promised 163.
   --- End of inner exception stack trace ---
   at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
```

Further technical details
.NetCoreApp 3.1
YARP 1.1.1
Kestrel

Can fix this bug  in the latest daily for 1.1.1?

**Comment by MihaZupan** [comment]
Do you have any code interacting with the request body before you call into YARP?
Seeing this exception generally indicates that the application has already read the request content before forwarding.

**Comment by 3087897260** [comment]
> Do you have any code interacting with the request body before you call into YARP? Seeing this exception generally indicates that the application has already read the request content before forwarding.
not have any code interacting with the request body before you call into YARP
issues: https://github.com/microsoft/reverse-proxy/pull/2111,but the version is yarp2.0.0

**Comment by 3087897260** [comment]
> Do you have any code interacting with the request body before you call into YARP? Seeing this exception generally indicates that the application has already read the request content before forwarding.
not have any code interacting with the request body before you call into YARP
issues: https://github.com/microsoft/reverse-proxy/pull/2111,but the version is yarp2.0.0

**Comment by waleswood** [comment]
Can share how to solve this problem?  @3087897260
