### ISSUE TITLE
Running YARP KubernetesIngress.Sample gives 'Forbidden' (403) exception when calling k8s API

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [microsoft/reverse-proxy#2141]
### Describe the bug
Trying to run .\samples\KubernetesIngress.Sample which has an Ingress + Monitor parts.  Built both components, installed them into Minikube but `yarp-controller` is getting a `Forbidden` error when trying to retrieve _ingresses_ resource

### To Reproduce
Commit: be58d842a8d8f57ed511afbb46a43984050eef4b

#### Steps to reproduce:
1. build `.\samples\KubernetesIngress.Sample\Ingress\`
2. build `.\samples\KubernetesIngress.Sample\Monitor\`
3. install into kubernetes:
3.1 `kubectl apply -f .\samples\KubernetesIngress.Sample\Ingress\ingress.yaml`
3.2 `kubectl apply -f .\samples\KubernetesIngress.Sample\Monitor\ingress-monitor.yaml`
4. examine logs for `yarp-controller`:

**Observed result:**
```bash
$ kubectl get pod -n yarp
NAME                               READY   STATUS    RESTARTS   AGE
yarp-controller-5f9bb97f8c-x62dw   1/1     Running   0          19h
yarp-proxy-5fb4d65b7b-p99lg        1/1     Running   0          20h

$ kubectl logs yarp-controller-5f9bb97f8c-x62dw -n yarp
...
[09:44:24 DBG] Informer V1Endpoints received Modified notification for Endpoints/k8s.io-minikube-hostpath.kube-system at resource version 784434
[09:44:25 INF] []
[09:44:25 INF] []
[09:44:25 WRN] Uncaught exception occured while reconciling
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICoreV1Operations.ReadNamespacedServiceStatusWithHttpMessagesAsync(String name, String namespaceParameter, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.CoreV1OperationsExtensions.ReadNamespacedServiceStatusAsync(ICoreV1Operations operations, String name, String namespaceParameter, Nullable`1 pretty, CancellationToken cancellationToken)
   at Yarp.Kubernetes.Controller.Client.V1IngressResourceStatusUpdater.UpdateStatusAsync() in /src/src/Kubernetes.Controller/Client/V1IngressResourceStatusUpdater.cs:line 50
   at Yarp.Kubernetes.Controller.Services.Reconciler.ProcessAsync(CancellationToken cancellationToken) in /src/src/Kubernetes.Controller/Services/Reconciler.cs:line 78
[09:44:25 INF] Rescheduling Ingress Change
```

**Expected result:**
no exceptions

### Observations
RBAC (role based access control) is setup in `.\samples\KubernetesIngress.Sample\Monitor\ingress-monitor.yaml` and this looks like it *should* work...

### Further technical details

Windows 10 Professional

```bash
$ docker --version
Docker version 20.10.24, build 297e128
```

```bash
$ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

**Comment by MihaZupan** [comment]
Likely a duplicate of #2018

Can you please try rebuilding with the current `main`?
A change was merged just yesterday that likely resolves this issue - #2136.

**Comment by TrevorDArcyEvans** [comment]
Thanks for the prompt response.  It seems to be working now with the latest commit from `main`.
