### ISSUE TITLE
Failure to log request body

### ISSUE THREAD

**Issue by johnkors** [microsoft/reverse-proxy#2172]
### Describe the bug
Requests through YARP does not log the body of the request, while requests handled outside of YARP does.

### To Reproduce

```csharp
app.UseSerilogRequestLogging(options =>
{
    options.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>
    {
        var body = GetRawBodyAsync(httpContext.Request).GetAwaiter().GetResult();
        diagnosticContext.Set("RequestBody", body);
    };
    
    async Task<string> GetRawBodyAsync(HttpRequest request)
    {
        request.EnableBuffering();
        using var reader = new StreamReader(request.Body, Encoding.UTF8);
        var body = await reader.ReadToEndAsync();
        request.Body.Position = 0;
        return body;
    }
});

app.MapReverseProxy(); // 👈 Filtered on certain endpoints & cannot log response body
app.Map("/{**catchall}", Results.BadRequest); // logs response body just fine
```

### Further technical details

Using
```csproj
<PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
<PackageReference Include="Yarp.ReverseProxy" Version="2.0.1" />
```

and .NET 7 on macOs and Linux (does not matter which, fails on both platforms)

The failure is not related to Serilog Request Logging. The same happens if one uses a raw middleware or the MS equivalent `app.UseHttpLogging();`

**Comment by johnkors** [comment]
Starting to believe this is more of a ASP.NET Core 6/7/8 issue than YARP…

**Comment by johnkors** [comment]
Yeah, so far this looks like an ASP.NET Core thing. I've tried these 3 approaches:

## 1 Serilog
```csharp
app.UseSerilogRequestLogging(options =>
{
    options.EnrichDiagnosticContext = async (diagnosticContext, httpContext) =>
    {
        var body = GetRawBodyAsync(httpContext.Request).GetAwaiter().GetResult();
        diagnosticContext.Set("RequestBody", body);         
    };
});
```

## 2 UseHttpLogging

Configured to log all fields and body size to max:

```csharp
 app.UseHttpLogging();
```

## 3 My own middleware

```csharp
app.Use(async (context, next) =>
 {
     var logger = context.RequestServices.GetService<ILogger<Program>>();
     var bod = await GetRawBodyAsync(context.Request);
     logger.LogWarning("body is {ReqBody}",bod);
     await next();
 });
```

### Helper for Serilog + Custom middleware:

```csharp
async Task<string> GetRawBodyAsync(HttpRequest request)
{
    request.EnableBuffering();
    using var reader = new StreamReader(request.Body, Encoding.UTF8);
    var body = await reader.ReadToEndAsync().ConfigureAwait(false);
    request.Body.Position = 0;
    return body;
}
```

**Comment by johnkors** [comment]
I get this error for my custom middleware, so perhaps I'm not rewinding the body stream correctly?
> RequestBodyClient: The client reported an error when copying the request body.

**Comment by Tratcher** [comment]
> RequestBodyClient: The client reported an error when copying the request body.

There should be an exception to go with this?

**Comment by johnkors** [comment]
Anyhoo – given that I've tried and failed miserably long enough. Could you let me know how one may/can/should properly log the request body of a proxied request..?

**Comment by johnkors** [comment]
> There should be an exception to go with this?

Nope. Logs when running custom middleware:

```log
[WRN][Program][{RequestId="0HMRN9BCPOFTQ:00000001", RequestPath="/health", ConnectionId="0HMRN9BCPOFTQ"}] body is {
  "john": "test"
}
[INF][Microsoft.AspNetCore.Routing.EndpointMiddleware][{EventId={Name="ExecutingEndpoint"}, RequestId="0HMRN9BCPOFTQ:00000001", RequestPath="/health", ConnectionId="0HMRN9BCPOFTQ"}] Executing endpoint 'r2'
[INF][Yarp.ReverseProxy.Forwarder.HttpForwarder][{EventId={Id=9, Name="Forwarding"}, RequestId="0HMRN9BCPOFTQ:00000001", RequestPath="/health", ConnectionId="0HMRN9BCPOFTQ"}] Proxying to https://www.proxyhost.com HTTP/2 RequestVersionOrLower no-streaming
[INF][Yarp.ReverseProxy.Forwarder.HttpForwarder][{EventId={Id=48, Name="ForwardingError"}, RequestId="0HMRN9BCPOFTQ:00000001", RequestPath="/health", ConnectionId="0HMRN9BCPOFTQ"}] RequestBodyClient: The client reported an error when copying the request body.
[INF][Microsoft.AspNetCore.Routing.EndpointMiddleware][{EventId={Id=1, Name="ExecutedEndpoint"}, RequestId="0HMRN9BCPOFTQ:00000001", RequestPath="/health", ConnectionId="0HMRN9BCPOFTQ"}] Executed endpoint 'r2'
[INF][Microsoft.AspNetCore.Hosting.Diagnostics][{ElapsedMilliseconds=428.4654, StatusCode=400, ContentType=null, ContentLength=0, Protocol="HTTP/1.1", Method="POST", Scheme="http", Host="localhost:8080", PathBase="", Path="/health", QueryString="", EventId={Id=2}, RequestId="0HMRN9BCPOFTQ:00000001", RequestPath="/health", ConnectionId="0HMRN9BCPOFTQ"}] Request finished HTTP/1.1 POST http://localhost:8080/health application/json 19 - 400 0 - 428.4654ms
```

**Comment by johnkors** [comment]
Sorry - a bit quick there. Seems like there _is_ an exception. It was hidden in an INFO level log statement. 

```
[INF][Yarp.ReverseProxy.Forwarder.HttpForwarder][{EventId={Id=48, Name="ForwardingError"}, RequestId="0HMRNADD3ACEN:00000001", RequestPath="/health", ConnectionId="0HMRNADD3ACEN"}] RequestBodyClient: The client reported an error when copying the request body.
System.AggregateException: One or more errors occurred. (Cannot access a disposed object.
Object name: 'System.String'.) (An error occurred while sending the request.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.String'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, Boolean autoFlush, CancellationToken cancellation)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: An error occurred when reading the request body from the client.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.String'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, Boolean autoFlush, CancellationToken cancellation)
   --- End of inner exception stack trace ---
   at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)<---
```

**Comment by johnkors** [comment]
I don't even get requestbody logs when doing this, so most likely a httplogger/aspnetcore issue.

```csharp
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHttpLogging(c =>
{
  c.LoggingFields = HttpLoggingFields.RequestBody |
                    HttpLoggingFields.RequestPath |
                    HttpLoggingFields.ResponseBody;
});

var app = builder.Build();

app.UseHttpLogging();
app.MapPost("/", () => "Hello POST!");

app.Run();
```

**Comment by Tratcher** [comment]
Ah, that exception helps. StreamReader closes the inner stream by default, you need to set the leaveOpen option to avoid that.
https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=net-7.0#system-io-streamreader-ctor(system-io-stream-system-text-encoding-system-boolean-system-int32-system-boolean)

**Comment by johnkors** [comment]
Filed this ticket at ASP.NET Core repo: https://github.com/dotnet/aspnetcore/issues/49063 , since it's not YARP specific.

**Comment by Tratcher** [comment]
@johnkors have each of these cases been resolved?

**Comment by johnkors** [comment]
Yep! Thanks! Closing.
