### ISSUE TITLE
Cluster config validation does not error on a null destination address

### ISSUE THREAD

**Issue by hahn-kev** [microsoft/reverse-proxy#2175]
### Describe the bug
I'm trying to make sure my config is valid on startup instead of later when we try to use it. To that end I setup a simple hosted service that will get the config on start and run the endpoints and clusters through the validator and throw if there's an error. However even with a null destination address I don't get any warnings.

### To Reproduce
setup a yarp with a basic route config and this as your cluster config:
```json
"Clusters": {
  "hgWeb": {
    "Destinations": {
      "hgWebServer": {
            "Address": null
      }
    }
  },
}
```
validation doesn't throw an error, however when you try to use the route you obviously get an exception:
```
      System.ArgumentNullException: Value cannot be null. (Parameter 'destinationPrefix')
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderReq
uestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
         at LexSyncReverseProxy.ProxyKernel.<>c.<<MapSyncProxy>b__1_1>d.MoveNext() in C:\dev\LexBox\backend\SyncReverseProxy\ProxyKernel.cs:line 74
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

### Further technical details

- version: 2.0.1
- windows 11

**Comment by Tratcher** [comment]
We try not to be too strict about destnation address validation to avoid blocking customization like UDS. That said, I don't know if there's a valid scenario for 'null' or empty ''.

**Comment by adityamandaleeka** [comment]
We would welcome a PR to add this check to the validation logic.
