### ISSUE TITLE
Context disposed after calling ReassignProxyRequest with a different RouteModel.

### ISSUE THREAD

**Issue by yassinebennani** [microsoft/reverse-proxy#2249]
### Describe the bug
Context disposed after calling ReassignProxyRequest with a different RouteModel.

### To Reproduce

What steps can we follow to reproduce the issue?
    Configure 2 routes each one reference a different cluster with a different destination
    Add a middleware and try to redirect from the first route to the second route 
    RouteModel route_model = this._lookup.GetRoutes().First(r => r.Config.RouteId == key);
    context.ReassignProxyRequest(route_model, route_model.Cluster);
    await this._next(context); //Exception
    Unable to access context after

Got Exceptions? Include both the message and the stack trace
--> Context is disposed and a not handled exception is thrown in the HttpForwarder.cs
       System.ObjectDisposedException: 'IFeatureCollection has been disposed.
       Object name: 'Collection'.'
      
      //Line 326
       finally
        {
            activityCancellationSource.Return();
            ForwarderTelemetry.Log.ForwarderStop(context.Response.StatusCode); // on this line while trying to access Response
        }

   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.get_StatusCode()
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.<SendAsync>d__8.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.<Invoke>d__5.MoveNext()

### Further technical details
   NB : The http request to the new route is sent successfully. 
- Include the version of the packages you are using
- dotnet 7
- yarp 2.0.1
- The platform (Linux/macOS/Windows)

**Comment by yassinebennani** [comment]
Even if I use only a different ClusterState for the original route model I have the same behavior and exception

**Comment by Tratcher** [comment]
ReassignProxyRequest shouldn't cause an ODE on the IFeatureCollection, it sounds like there's a lifetime issue with the HttpContext. Can you give a more complete repro for your scenario?

**Comment by adityamandaleeka** [comment]
@yassinebennani Do you think you'll be able to provide a repro for this?

**Comment by karelz** [comment]
Triage: No response, closing. Feel free to reopen if there is actionable repro for further investigation.
