### ISSUE TITLE
System.Net.Http.HttpRequestException: Connection refused (502 Response)

### ISSUE THREAD

**Issue by asafdl** [microsoft/reverse-proxy#2484]
### Describe the bug
In K8s environment, consider this case:
1. Request comes in to YARP
2. YARP forwards to one of the destinations in the destination list that it receives from the k8s (api server) ingress resource.
3. In the meantime the destination has shutdown (there is a small window where k8s is between `/ready` scrapes and doesn't know server is down)
4. There is now a race condition:
    a. YARP's list of destinations (in ingress) is updated before request is forwarded -> send it an available server
    b. Request leaves YARP before list for destinations is updated -> possible send to a down server -> connection refused by server -> returns `502` to client

I don't think in k8s you can avoid this race condition, the k8s api server needs to scrape the `/ready` endpoint, and if requests are constantly running through the YARP, it seems very likely that some requests will end up being sent to a server that is not ready.

This results in an avoidable 502 error for clients

#### Expected
I would like YARP to be able to handle this common race condition edge case, if connection is actively refused from server then try to find a different destination as fallback.

### To Reproduce
1. Set up a K8s YARP that forwards high volume of requests to internal k8s pod.
2. In your "server" have the readiness probe fail at random intervals
3. Expect to see some `System.Net.Http.HttpRequestException: Connection refused` Errors

### Further technical details

- Include the version of the packages you are using
```
    <PackageReference Include="Yarp.Kubernetes.Controller" Version="2.1.0-preview.1.23563.7" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.1.0-preview.1.23563.7" />
    <PackageReference Include="Yarp.Telemetry.Consumption" Version="2.1.0-preview.1.23563.7" />
```
- The platform (Linux/macOS/Windows)
Linux, K8s

### Logs

```
{"Category":"Yarp.ReverseProxy.Forwarder.HttpForwarder", "EventId":48, "Exception":"System.Net.Http.HttpRequestException: Connection refused (******:8080)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.Metrics.MetricsHandler.SendAsyncWithMetrics(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context,… [message truncated due to size]
```

Brief timeline gathered from logs:
```
YARP side:
14:55:51.096 - Request processing start in YARP
14:55:51.641 - Connection Refused Error (shown above)
14:55:52.184 - YARP Reconciler Informer class reevaluates Ingress resource
Server side:
2024-04-08T14:55:50.263Z - Shutting down gracefully...
2024-04-08T14:55:51.039Z - Shutting down complete
```

**Comment by MihaZupan** [comment]
Thank you for the nice description. This sounds reasonable but I don't know that we would do anything specific to K8s here. This sort of race condition exists in all configurations where destinations may become unhealthy.

I'll close this as a duplicate against #56 since failing to even connect to a destination is a case that would be considered "safe to retry". Please let me know if you think there's something else we could be doing here for K8s, or feel free to comment on #56.
