### ISSUE TITLE
Timeout on route config has no effect

### ISSUE THREAD

**Issue by nazirj-absa** [microsoft/reverse-proxy#2538]
Setting the timeout on a route level in YARP 2.1.0 resulted in an error.
Using 2.2.0-preview.1.24266, the timeout value is ignored on a route level.

Yarp - 2.2.0-preview.1.24266.1

**Comment by MihaZupan** [comment]
Can you share a minimal runnable example?

Note that these timeouts don't apply when running under a debugger.

**Comment by nazirj-absa** [comment]
Tried in release mode, running the app from powershell.

`using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.RateLimiting;
using System.Security.Authentication;
using Yarp.ReverseProxy.Configuration;
using Yarp.ReverseProxy.Forwarder;
using Yarp.ReverseProxy.Transforms;

internal class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddEndpointsApiExplorer();
        builder.Services.AddSwaggerGen();

        builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer();

        builder.Services.AddAuthorization(options =>
        {
            options.AddPolicy("authenticated", policy =>
                policy.RequireAuthenticatedUser());
        });

        builder.Services.AddRateLimiter(rateLimiterOptions =>
        {
            rateLimiterOptions.AddFixedWindowLimiter("fixed", options =>
            {
                options.Window = TimeSpan.FromSeconds(10);
                options.PermitLimit = 10;
            });
        });

        //builder.Services
        //    .AddReverseProxy()
        //    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

        builder.Services.AddReverseProxy()
            .LoadFromMemory(GetRoutes(), GetClusters());

        var app = builder.Build();

        if (app.Environment.IsDevelopment())
        {
            app.UseSwagger();
            app.UseSwaggerUI();
        }

        app.UseHttpsRedirection();

        app.UseAuthentication();

        app.UseAuthorization();

        app.UseRateLimiter();

        app.MapGet("/test", () =>
        {
            return new string[] { "value1", "value2" };
        });

        app.MapReverseProxy();


        app.Run();
    }

    private static IReadOnlyList<RouteConfig> GetRoutes()
    {
        var routekv = new Dictionary<string, string>();
        routekv.Add("/api-integration/getwithdelay", "/apigw/integration/getitemswithdelay");
        routekv.Add("/api-integration/simplecreate", "/apigw/integration/createitem");
        routekv.Add("/api-integration/simpleupdate", "/apigw/integration/updateitem");
        routekv.Add("/api-integration/simpleget", "/apigw/integration/getItems");

        var routes = new List<RouteConfig>();

        foreach (var kv in routekv)
        {
            var routeItem = new RouteConfig
            {
                RouteId = $"test{kv.Key.Replace('/','-')}",
                ClusterId = "test-cluster-dev",
                RateLimiterPolicy = "fixed",
                MaxRequestBodySize = 300,
                Timeout = TimeSpan.FromSeconds(10),
                Match = new RouteMatch
                {
                    Path = kv.Key
                },
                Transforms = new[]
                {
                    new Dictionary<string, string> { { "PathSet", kv.Value } }
                }
            };
            routeItem = routeItem.WithTransformResponseHeader(headerName: "RequestProcessedBy",
                value: "TestServerForYARP", append: true, ResponseCondition.Always);
            routes.Add(routeItem);
        }

        return routes;
    }

    private static IReadOnlyList<ClusterConfig> GetClusters()
    {
        return new[]
        {
            new ClusterConfig
            {
                ClusterId = "test-cluster-dev",
                HttpClient = new HttpClientConfig
                {
                    SslProtocols = SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13,
                    MaxConnectionsPerServer = 10,
                    DangerousAcceptAnyServerCertificate = true
                },
                HttpRequest = new ForwarderRequestConfig
                {
                    ActivityTimeout = TimeSpan.FromMinutes(2)
                },
                Destinations = new Dictionary<string, DestinationConfig>
                {
                    { "destination1", new DestinationConfig { Address = "https://example.com" } }
                }
            },
        };
    }
}
`

**Comment by MihaZupan** [comment]
> The timeout was not applied for route 'test-api-integration-getwithdelay', ensure `IApplicationBuilder.UseRequestTimeouts()` is called between `IApplicationBuilder.UseRouting()` and `IApplicationBuilder.UseEndpoints()`.

**Comment by nazirj-absa** [comment]
I tried this but I get another error.
Can you share a sample of how you got this work, using code?
Thanks so much for your assistance.
```
C:\source\research\yarp-api-gateway-sample\Yarp.Gateway\bin\Release\net8.0 [(main)]> .\Yarp.Gateway.exe
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\ab016zo\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.Timeouts.ICancellationTokenLinker' while attempting to activate 'Microsoft.AspNetCore.Http.Timeouts.RequestTimeoutsMiddleware'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.Timeouts.ICancellationTokenLinker' while attempting to activate 'Microsoft.AspNetCore.Http.Timeouts.RequestTimeoutsMiddleware'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.Timeouts.ICancellationTokenLinker' while attempting to activate 'Microsoft.AspNetCore.Http.Timeouts.RequestTimeoutsMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.Main(String[] args) in C:\source\research\yarp-api-gateway-sample\Yarp.Gateway\Program.cs:line 68
C:\source\research\yarp-api-gateway-sample\Yarp.Gateway\bin\Release\net8.0 [(main)]>
```

**Comment by MihaZupan** [comment]
You also need `AddRequestTimeouts`.

e.g.

```c#
builder.Services.AddRequestTimeouts();

var app = builder.Build();

app.UseRequestTimeouts();
app.MapReverseProxy();
```

**Comment by nazirj-absa** [comment]
That works. Thank you so much.

**Comment by CwjXFH** [comment]
Hi, 
I have the same problem with .NET 8 and YARP `2.2.0-preview.1.24266.1`, my route config is:

```json
{
  "ReverseProxy": {
    "Routes": {
      "test_header_route": {
        "ClusterId": "test_cluster",
        "Timeout": "00:00:01",
        "Match": {
          "Hosts": [
            "*"
          ],
          "Headers": [
            {
              "Name": "X-Custome-Id",
              "Values": [
                "666"
              ],
              "Mode": "ExactHeader"
            }
          ]
        }
      }
    },
    "Clusters": {
      "test_cluster": {
        "Destinations": {
          "node1": {
            "Address": "https://www.google.com",
            "Methods": [
              "POST",
              "GET"
            ]
          }
        }
      }
    }
  }
}
```

```c#
var builder = WebApplication.CreateBuilder(args);

builder.Services
	// .AddRequestTimeouts(opt => opt.DefaultPolicy = new Microsoft.AspNetCore.Http.Timeouts.RequestTimeoutPolicy { Timeout = TimeSpan.FromSeconds(1) })
	.AddRequestTimeouts()
	.AddReverseProxy()
	.LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

var app = builder.Build();
app.UseRequestTimeouts();
app.MapReverseProxy();
await app.RunAsync();
```

The `Timeout` configuration is not working.
