### ISSUE TITLE
server-sent-events stream not terminating

### ISSUE THREAD

**Issue by rstutton** [microsoft/reverse-proxy#461]
I have a server-sent-events (it returns "text/event-stream" streams) api from an asp.net 4 application - which my client can connect to using yarp - it maintains very long running (many days) connections with no issues, messages are delivered normally. However, if the client disconnects the server doesn't see the disconnection and and the stream isn't closed - it can continue to write as if the client is still there. Yarp has logged the disconnect "Request finished in X ms 200 text/event-stream", but the upstream server doesn't see the disconnect.
The full output from yarp is like this:
```
[20:09:45 INF] Operation ended: ReverseProxy.Proxy, 129876.7893ms, error: The operation was canceled.
[20:09:45 INF] Executed endpoint 'pulse'
[20:09:45 INF] HTTP GET /pulse?t=[trimmed url] responded 200 in 129884.2091 ms
[20:09:45 INF] Request finished in 129888.0948ms 200 text/event-stream
```

If I terminate yarp, the server immediately sees the client as having gone - i.e. even though the client has long gone, the upstream server doesn't notice until I kill yarp - which is why I think yarp is holding the tcp connection open.
If I connect directly to the server without yarp, the server will see immediately when the client disconnects.

No exceptions are produced 

I am developing this on Windows 10 for use on Windows Server 2016 & 2019. The upstream server is IIS, running asp.net 4, .net framework 4.8.
The reverse proxy application is a .net core 3.1 application using kestrel, running yarp preview 5. The reverse proxy application and the upstream server reside on the same box.

**Comment by Tratcher** [comment]
Hmm. `Operation ended: ReverseProxy.Proxy, 129876.7893ms, error: The operation was canceled.` means an OperationCancelledException was caught and logged here:
https://github.com/microsoft/reverse-proxy/blob/4bd161b6b357e2f146159dd8aef843b6e67fc4a7/src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs#L91-L93

Preview5 includes a bunch of new error handling in HttpProxy, an exception shouldn't have escaped. It should also have been logged like this:
https://github.com/microsoft/reverse-proxy/blob/4bd161b6b357e2f146159dd8aef843b6e67fc4a7/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L788-L791

Are you sure you're not running preview4? The lack of that log and the escaping exception seem like preview4 behavior.

The request would have been in the CopyResponseBody stage here:
https://github.com/microsoft/reverse-proxy/blob/4bd161b6b357e2f146159dd8aef843b6e67fc4a7/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L618-L619

Failing to disconnect with the destination implies a failure to close/reset the connection when copying the response body was cancelled. There's a using on that destinationResponseStream so it should always be closed. It's possible the SocketsHttpHandler isn't closing/resetting the connection for some reason?

Do you know if the connection to the destination is using HTTP/1.1 or HTTP/2? HTTP/2 is the default if you're using TLS/HTTPS to the destination. HTTP/1.1 would close the whole connection, where HTTP/2 would only reset the one request stream. Either should register as a disconnection on the destination though.

**Comment by rstutton** [comment]
Thanks for your comments; and I apologize, it turns out that it was actually preview 4.
With preview5 the output is indeed different *and* the connection is properly closed to the upstream server. 
Closing this issue. Thanks for the product too - very useful.

```
[14:25:11 INF] ResponseBodyCanceled: Copying the response body was canceled.
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.CancellationHelper.ThrowOperationCanceledException(Exception innerException, CancellationToken cancellationToken)
   at System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.GetCancelableWaiterTask(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.StreamCopier.CopyAsync(Stream input, Stream output, CancellationToken cancellation)
[14:25:11 INF] Operation ended: ReverseProxy.Proxy, 34988.409ms, success
[14:25:11 INF] Executed endpoint 'pulse'
[14:25:11 INF] HTTP GET /pulse?t=[trimmed url] responded 200 in 35359.0192 ms
[14:25:11 INF] Request finished in 35367.1177ms 200 text/event-stream
```
