### ISSUE TITLE
502 Bad Gateway when switching from localhost to specific address

### ISSUE THREAD

**Issue by Flearz** [microsoft/reverse-proxy#563]
### Describe the bug
Hello, my code is totally working when using the localhost adress but when I switch it to a personalized one (myaddress.net) it stops working.
My hosts file:
```
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
# MyAdress
127.0.0.1       myaddress .net
```

my launchsettings
```
  "TestReverseProxyYarp.Server": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": "true",
      "applicationUrl": "https://myaddress.net:44390;",
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
    }
```

my appsettings:
```
"ReverseProxy": {
    "Routes": [
      //{
      //  "RouteId": "WeatherForecast",
      //  "ClusterId": "cluster3",
      //  "Match": {
      //    "Methods": [ "GET", "POST" ],
      //    //"Host": "localhost",
      //    "Path": "/WeatherForecast2"
      //  }
      //},
      {
        "RouteId": "WeatherForecast",
        "ClusterId": "cluster4",
        "Match": {
          "Methods": [ "GET", "POST" ],
          //"Host": "myaddress.net",
          "Path": "/WeatherForecast2"
        }
      }
    ],
    "Clusters": {
      "cluster3": {
        "Destinations": {
          "cluster3/destination1": {
            "Address": "https://localhost:5001/"
          }
        }
      },
      "cluster4": {
        "Destinations": {
          "cluster4/destination1": {
            "Address": "https://myaddress.net:5001/"
          }
        }
      }
    }
  }
```

My startup.cs:
```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddControllersWithViews();
            services.AddReverseProxy()
  .LoadFromConfig(Configuration.GetSection("ReverseProxy"));
            services.AddRazorPages();

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
          
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebAssemblyDebugging();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                //endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapReverseProxy();
                //endpoints.MapFallbackToFile("index.html"); 
           
            });
        }
    }
```

And I used the sample "WeatherForecasts" Api where I changed the address to https://myaddress.net:5001 
I made requests with postman on https://myaddress.net:44390/WeatherForecast2 and get a 502 bad gateway.
When I had it all on localhost, it was perfectly working..

Sorry if I did a dumb thing, it's my first reverse  proxy :)

P.S. for an obscure reason, my console show infos that it's in development environment but in the en it says that the Hosting environment is production... So I can't have any debug infos. If you have any idea :)

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://[::]:44390
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\iAi\Projets\AIMM\Tests\TestReverseProxyYarp\TestReverseProxyYarp\Server
Hosting environment: Production
```

**Comment by Tratcher** [comment]
That extra `Hosting environment: Production` is really weird. What does your program.cs look like? Also your full appsettings.json and appsettings.development.json.

**Comment by Flearz** [comment]
Ok, my appsettings was wrong, I now have debug messages. Thanks.
Now I am trying to get the request from the client, which has no certificate and then pass it to the proxy, which have a certificate and then proxy it to a server which requires the certificate. Is that possible ?

**Comment by Flearz** [comment]
> 
> 
> Ok, my appsettings was wrong, I now have debug messages. Thanks.
> Now I am trying to get the request from the client, which has no certificate and then pass it to the proxy, which have a certificate and then proxy it to a server which requires the certificate. Is that possible ?
> I get this error:
> The HTTP/2 server reset the stream. HTTP/2 error code 'HTTP_1_1_REQUIRED' (0xd).

I managed to use HTTP1.1 but now I have 403 forbidden even though I changed my appsettings to use a certificate: 
```
 "Clusters": {
      "cluster1": {
        "HttpClientOptions": {
          "SslProtocols": [
            "Tls12"
          ],
          //"ValidateRemoteCertificate": "true",
          //"DangerousAcceptAnyServerCertificate": "true",
          "ClientCertificate": {
            "Path": "C:/Users/xxxx/Desktop/yyyyyy.pfx",
            "Password": "xxxxx"
          }
        },
        "HttpRequest": {
          "Version": "1.1"
        },
        "Destinations": {
          "cluster1/destination1": {
            "Address": "https://myaddress.net:44367/"

          }
        }
      }
```

**Comment by Tratcher** [comment]
What is the destination server and how is it's client certificate requirement configured on that server? Getting HTTP_1_1_REQUIRED is surprising.

**Comment by Flearz** [comment]
Thanks for the answer.
I am using the WeatherForecast .net core 3 Web API template.
I just configured IIS to use the right certificate:
I just added  `<access sslFlags="Ssl, SslNegotiateCert, SslRequireCert" />` in applicationhost.config 
and did
```
c:\Program Files (x86)\IIS Express>IisExpressAdminCmd.exe setupSslUrl -url:https://myaddress.net:44350/ -CertHash:4987855a9794303b9f7af2d9265e5500f795e0b1
Command 'setupSslUrl' completed.
```

Here is the complete error when using HTTP/2 request
```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET https://myaddress.net:44390/WeatherForecast2 application/json 81
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: The request path /WeatherForecast2 does not match a supported file type
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 2 candidate(s) found for the request path '/WeatherForecast2'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'WeatherForecast' with route pattern '/WeatherForecast2' is valid for the request path '/WeatherForecast2'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/WeatherForecast2'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'WeatherForecast'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'WeatherForecast'
Proxy.Middleware: Debug: Iterating Destinations
Proxy.Middleware: Debug: Destination ID: cluster4/destination1
Address: https://myaddress.net:44350/
Microsoft.ReverseProxy.Service.Proxy.HttpProxy: Information: Proxying to https://myaddress.net:44350/WeatherForecast2
Exception thrown: 'System.IO.IOException' in System.Net.Http.dll
Exception thrown: 'System.IO.IOException' in System.Net.Http.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Microsoft.ReverseProxy.Service.Proxy.HttpProxy: Information: Request: An error was encountered before receiving a response.

System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'HTTP_1_1_REQUIRED' (0xd).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions proxyOptions)
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'WeatherForecast'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/1.1 GET https://myaddress.net:44390/WeatherForecast2 application/json 81 - 502 - - 671.9783ms
```

If I force http 1.1 I get "Forbidden" else I get "502 bad gateway"

**Comment by samsp-msft** [comment]
@Tratcher - moving back above the fold as it probably got lost during the break.

**Comment by Tratcher** [comment]
Ah. HTTP/2 doesn't support per-route or per app client certificate requirements, a client cert must be negotiated as part of opening the connection. The only place I know how to set that in IIS/Express is with the netsh.exe command under `netsh http add sslcert` setting the `clientcertnegotiation` property.

Is there a reason you need to do this with IIS/Express? With Kestrel at least you'd be able to do it in code or appsettings.json.

> If I force http 1.1 I get "Forbidden" else I get "502 bad gateway"

You'll need to look at the destination server logs to understand why. How are you authenticating the client certificate in the destination app?

**Comment by karelz** [comment]
Triage: Seems to be answered. If there are more questions/follow ups, let's move it to Discussions.
