### ISSUE TITLE
YARP config doesn't support a negative order

### ISSUE THREAD

**Issue by NGloreous** [microsoft/reverse-proxy#565]
### Describe the bug
If you try to provide a negative value for a proxy route order, config load fails with a InvalidOperationException due to a FormatException when parsing the order.

The issue is in ConfigurationReadingExtensions.cs, ReadInt32 calls int.Parse passing in NumberStyles.None which doesn't allow negative values. 

```c#
        internal static int? ReadInt32(this IConfiguration configuration, string name)
        {
            return configuration[name] is string value ? int.Parse(value, NumberStyles.None, CultureInfo.InvariantCulture) : null;
        }
```

Since the default order is 0, it would be nice to be able to specify negative values so some routes take precedence over the routes with out order specified. 

### To Reproduce

Try using the following config:

```JSON
{
  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Order": -1,
        "Match": {
          "Path": "{**catch-all}"
        },
      }
    ],
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "cluster1/destination1": {
            "Address": "https://example.com/"
          }
        }
      }
    }
  }
}
```

```
System.InvalidOperationException: Unable to load or apply the proxy configuration.
       ---> System.FormatException: Input string was not in a correct format.
         at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
         at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
         at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
         at Microsoft.Extensions.Configuration.ConfigurationReadingExtensions.ReadInt32(IConfiguration configuration, String name)
         at Microsoft.ReverseProxy.Configuration.ConfigurationConfigProvider.CreateRoute(IConfigurationSection section)
         at Microsoft.ReverseProxy.Configuration.ConfigurationConfigProvider.UpdateSnapshot()
         at Microsoft.ReverseProxy.Configuration.ConfigurationConfigProvider.GetConfig()
         at Microsoft.ReverseProxy.Service.Management.ProxyConfigManager.InitialLoadAsync()
```

**Comment by Tratcher** [comment]
This was a regression when we refactored the config bindings. Should be an easy fix.
