### ISSUE TITLE
Destination address is not validated.

### ISSUE THREAD

**Issue by ManickaP** [microsoft/reverse-proxy#765]
An invalid address can be passed to destination (in places like here: [`{ "destination1",  new Destination() { Address = destination.GetAddress() } }`](https://github.com/microsoft/reverse-proxy/blob/main/test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs#L80)). The property is string, anything can be passed in there.

Seems like we're missing validation of destinations in here:
https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Service/Config/ConfigValidator.cs#L117-L136

If this happens, the first request going to the destination will throw exception like this:
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Microsoft.ReverseProxy.Utilities.RequestUtilities.MakeDestinationAddress(String destinationPrefix, PathString path, QueryString query) in /home/manicka/Repositories/reverse-proxy.2/src/ReverseProxy/Utilities/RequestUtilities.cs:line 63
   at Microsoft.ReverseProxy.Service.RuntimeModel.Transforms.StructuredTransformer.TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, String destinationPrefix) in /home/manicka/Repositories/reverse-proxy.2/src/ReverseProxy/Service/RuntimeModel/Transforms/StructuredTransformer.cs:line 94
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, RequestProxyOptions requestOptions, Boolean isStreamingRequest, CancellationToken requestAborted) in /home/manicka/Repositories/reverse-proxy.2/src/ReverseProxy/Service/Proxy/HttpProxy.cs:line 282
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer) in /home/manicka/Repositories/reverse-proxy.2/src/ReverseProxy/Service/Proxy/HttpProxy.cs:line 119
   at Microsoft.ReverseProxy.Middleware.ProxyInvokerMiddleware.Invoke(HttpContext context) in /home/manicka/Repositories/reverse-proxy.2/src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs:line 81
   at Microsoft.ReverseProxy.Middleware.PassiveHealthCheckMiddleware.Invoke(HttpContext context) in /home/manicka/Repositories/reverse-proxy.2/src/ReverseProxy/Middleware/PassiveHealthCheckMiddleware.cs:line 27
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.ReverseProxy.HeaderEncodingTests.<>c__DisplayClass1_0.<<ProxyAsync_ResponseWithEncodedHeaderValue>b__3>d.MoveNext() in /home/manicka/Repositories/reverse-proxy.2/test/ReverseProxy.FunctionalTests/HeaderEncodingTests.cs:line 173
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task), Path = "/" }
   at Microsoft.ReverseProxy.HeaderEncodingTests.ProxyAsync_ResponseWithEncodedHeaderValue(String headerValue, String encodingName) in /home/manicka/Repositories/reverse-proxy.2/test/ReverseProxy.FunctionalTests/HeaderEncodingTests.cs:line 186
   at Microsoft.ReverseProxy.HeaderEncodingTests.ProxyAsync_ResponseWithEncodedHeaderValue(String headerValue, String encodingName) in /home/manicka/Repositories/reverse-proxy.2/test/ReverseProxy.FunctionalTests/HeaderEncodingTests.cs:line 201
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
   ```

**Comment by Tratcher** [comment]
@alnikola when investigating SF we found an example scenario for a different destination address format that made us re-consider how closely this field should be validated. Do you remember what that was? Something like `fabric://service`?

**Comment by Tratcher** [comment]
Found it: #569 `fabric:/appName/svcName`. Looking back, that would probobly be evaulated before creating a true Destination object so the validation wouldn't apply.

Proposal: We should at least try a Uri.TryParse on the input to make sure there's a scheme, host, etc.. I'd still be careful about validating it too closely and blocking out some extensibility scenarios like a named pipes transport.

**Comment by alnikola** [comment]
Yes, that was it.

**Comment by karelz** [comment]
Triage: We believe that customers will want to pass lots of random "stuff" here. Until we have more feedback, let's close it.
`Uri.TryParse` might be a good way to use, though `fabric:/` is not quite aligned with that :(
